/**
 * IPC Types Index
 * Unified export of all IPC-related type definitions
 *
 * This file aggregates and re-exports all types from the modular structure,
 * maintaining backward compatibility with existing imports from '../shared/ipc.js'
 */

// IPC Channel Constants
export { IPC_CHANNELS } from "./channels.js";

export {
	DEFAULT_AGENT_ID,
	agentIdentity,
	isColleague,
	isActiveAgent,
} from "./agents.js";
export type {
	CollabAgentActivityGetRequest,
	CollabAgentActivityGetResponse,
	CollabAgentActivitySnapshot,
	CollabAgentHeldLease,
	CollabAgentMind,
	CollabAgentWorkerCard,
	CollabBoard,
	CollabBoardAction,
	CollabBoardActRequest,
	CollabBoardActResponse,
	CollabBoardGetRequest,
	CollabBoardGetResponse,
	CollabDmRoomEnsureRequest,
	CollabDmRoomEnsureResponse,
	CollabMessageReactRequest,
	CollabMessageReactResponse,
	CollabRoomBudgetsPatch,
	CollabRoomBudgetsRequest,
	CollabRoomBudgetsResponse,
	CollabRoomFolderEntry,
	CollabRoomFolderListRequest,
	CollabRoomFolderListResponse,
	CollabRoomFrozenRequest,
	CollabRoomFrozenResponse,
	CollabCoordinatorBlockedBy,
	CollabCoordinatorGate,
	CollabCoordinatorGetRequest,
	CollabCoordinatorGetResponse,
	CollabCoordinatorJudgment,
	CollabCoordinatorLogEntry,
	CollabCoordinatorPhase,
	CollabCoordinatorQueued,
	CollabCoordinatorState,
	CollabCoordinatorTurn,
	CollabRoomClearHistoryRequest,
	CollabRoomClearHistoryResponse,
	CollabRoomSpendRequest,
	CollabRoomSpendResponse,
	CollabRoomUpdatePatch,
	CollabRoomUpdateRequest,
	CollabRoomUpdateResponse,
	CollabSchedulerLogEntry,
	CollabSchedulerLogTailRequest,
	CollabSchedulerLogTailResponse,
	CollabTask,
	CollabTaskEvidence,
	CollabTaskStatus,
	CollabTaskStopRequest,
	CollabTaskStopResponse,
} from "./collab.js";
export type {
	OriginTransport,
	ConversationType,
	ResolvedIdentityKind,
	ChannelActor,
	ChannelConversation,
	ReplyTarget,
	ResolvedIdentity,
	MessageOrigin,
	IMConnectorIncomingMessage,
	IMConnectorReplyPayload,
	IMConnector,
	ChannelUserLink,
	ChannelUserProfile,
	ChannelIdentityListProfilesResponse,
	ChannelIdentityCreateProfileRequest,
	ChannelIdentityCreateProfileResponse,
	ChannelIdentityUpdateProfileRequest,
	ChannelIdentityUpdateProfileResponse,
	ChannelIdentityListLinksRequest,
	ChannelIdentityListLinksResponse,
	ChannelIdentityCreateLinkRequest,
	ChannelIdentityCreateLinkResponse,
	ChannelIdentityDeleteLinkRequest,
	ChannelIdentityDeleteLinkResponse,
	ChannelIdentityResolveRequest,
	ChannelIdentityResolveResponse,
	ChannelReplyDeliveryRecord,
} from "./channel-identity.js";
export type {
	AgentDefinition,
	AgentIdentity,
	AgentKind,
	AgentStatus,
	AgentExecutor,
	AgentModelBinding,
	AgentsListResponse,
	AgentCreateRequest,
	AgentCreateResponse,
	AgentUpdateRequest,
	AgentUpdateResponse,
	AgentDeleteRequest,
	AgentDeleteResponse,
	AgentRemovalOutcome,
	AgentRestoreRequest,
	AgentRestoreResponse,
} from "./agents.js";

// IPC Router infrastructure
export { defineRouter, getChannelName } from "./router.js";
export type {
	RouteConfig,
	DomainRoutes,
	Router,
	RouteHandlers,
	RouteAPI,
} from "./router.js";

// Tool types
export type {
	GetToolsResponse,
	ExecuteToolRequest,
	ExecuteToolResponse,
	ToolParameter,
	ToolDefinition,
	ToolCall,
	DiffHunk,
	DiffHunkLine,
	ToolResultContentPart,
	ToolResult,
	ToolPartialResult,
	ToolExecutionMode,
	ToolRenderShell,
	ToolRenderKind,
	PermissionMode,
	BashToolSettings,
	ToolCallModelSettings,
	ToolSettings,
	StreamMessageChunk,
	SendMessageStreamResponse,
} from "./tools.js";

// Chat types
export type {
	VoiceASRProvider,
	VoiceTTSProvider,
	VoiceEndpointingMode,
	VoiceWakeSensitivity,
	VoiceDoubaoSettings,
	VoiceAudioChunkPayload,
	VoiceRuntimeStatus,
	VoiceWakeSettings,
	VoiceVADSettings,
	VoiceASRSettings,
	VoiceTTSSettings,
	VoiceConversationSettings,
	VoiceSettings,
	VoiceTranscriptMetadata,
	VoiceLatencyMilestone,
	VoiceLatencyMilestoneName,
	VoiceRuntimeState,
	VoiceEvent,
	VoiceRuntimeEvent,
	VoiceRuntimeCommand,
	VoiceStartRequest,
	VoiceStopRequest,
	VoiceSubmitUtteranceRequest,
	VoiceSubmitTranscriptRequest,
	VoiceSynthesizeRequest,
	VoiceTestASRRequest,
	VoiceTestTTSRequest,
	VoiceTTSModel,
	VoiceBaseResponse,
	VoiceGetStateResponse,
	VoiceSubmitUtteranceResponse,
	VoiceSynthesizeResponse,
	VoiceTTSModelsResponse,
} from "./voice.js";

export type {
	MusicPlayerBackend,
	MusicRadioSource,
	MusicSetupStage,
	MusicToolStatus,
	MusicEnvStatus,
	MusicRuntimeState,
	MusicBaseResponse,
	MusicListProvidersResponse,
	MusicGetProgrammeResponse,
	MusicOpenRadioRequest,
	MusicSearchRequest,
	MusicSearchResponse,
	MusicSearchRecordDTO,
	MusicRequestSongRequest,
	MusicRequestSongResponse,
	MusicProgrammeActionRequest,
	MusicProgrammeEntryDTO,
	MusicProgrammeAction,
	MusicProviderDescriptorDTO,
	MusicSetProviderRequest,
	MusicGetStateResponse,
	MusicSetupRequest,
	MusicSetupResponse,
	MusicEvent,
	MusicSettings,
	MusicNowPlaying,
	MusicCommand,
	MusicCommandRequest,
	MusicCommandResponse,
	MusicRadioState,
	MusicLyricLine,
	MusicLyrics,
	MusicDjSpeak,
} from "./music.js";

export type {
	ContextVariable,
	VariableLevel,
	ContentPart,
	StepType,
	Step,
	AttachmentMediaType,
	MessageAttachment,
	ChatMessage,
	ChatMessageMention,
	ChatMessageReaction,
	ChatMessageReactionActor,
	ChatMessageReplyTo,
	PromptContextRole,
	BaseInstructions,
	PromptContextMarker,
	PromptContextFragment,
	TurnContextSnapshot,
	PromptContextState,
	// Session-level optimization (Phase 4: Metadata Separation)
	SessionMeta,
	SessionDetails,
	ChatSession,
	SendMessageRequest,
	SendMessageResponse,
	EditAndResendRequest,
	EditAndResendResponse,
	GetChatHistoryRequest,
	GetChatHistoryResponse,
	GetSessionsResponse,
	CreateSessionRequest,
	CreateSessionResponse,
	SwitchSessionRequest,
	SwitchSessionResponse,
	DeleteSessionRequest,
	DeleteSessionResponse,
	RenameSessionRequest,
	RenameSessionResponse,
	CreateBranchRequest,
	CreateBranchResponse,
	UpdateSessionPinRequest,
	UpdateSessionPinResponse,
	GenerateTitleRequest,
	GenerateTitleResponse,
	SystemPromptToolSnapshot,
	SystemPromptSkillSnapshot,
	SystemPromptSnapshot,
	GetSystemPromptSnapshotRequest,
	GetSystemPromptSnapshotResponse,
	// Optimized session loading (Phase 4)
	GetSessionsListResponse,
	ActivateSessionResponse,
	GetSessionMessagesResponse,
	SessionMessagesPageDirection,
	SessionMessagesPageAnchor,
	GetSessionMessagesPageRequest,
	SessionMessagePageCursor,
	GetSessionMessagesPageResponse,
	UserMessageMarker,
	GetSessionUserMarkersResponse,
} from "./chat.js";

// Media types
export type {
	MediaKind,
	MediaSource,
	MediaUsageTag,
	MediaAssetLink,
	MediaAssetMetadata,
	MediaAsset,
	MediaQuery,
	MediaGalleryResponse,
	MediaRebuildResponse,
} from "./media.js";

// Markdown asset / attachment types
export type {
	MarkdownAssetKind,
	MarkdownAssetResolution,
	MarkdownResolveAssetRequest,
	MarkdownResolveAssetResponse,
	MarkdownAttachmentInput,
	SavedMarkdownAttachment,
	MarkdownSaveAttachmentsRequest,
	MarkdownSaveAttachmentsResponse,
} from "./markdown.js";

// Provider types
export type {
	AIProviderId,
	ThinkingEffort,
	OAuthFlowType,
	OAuthToken,
	OpenRouterModel,
	ProviderInfo,
	ProviderConfig,
	ModelCapabilityOverride,
	CustomProviderConfig,
	AISettings,
	ModelCapabilityEntry,
	ModelType,
	ModelInfo,
	GetProvidersResponse,
	CodexUsageWindow,
	CodexUsageCredits,
	CodexUsageLimit,
	CodexProviderUsage,
	ProviderUsageRequest,
	ProviderUsageResponse,
	ProviderEnvVarCandidate,
	ProviderEnvStatus,
	GetProviderEnvStatusRequest,
	GetProviderEnvStatusResponse,
} from "./providers.js";

export { AIProvider } from "./providers.js";

// MCP types
export type {
	MCPTransportType,
	MCPServerConfig,
	MCPConnectionStatus,
	MCPToolInfo,
	MCPResourceInfo,
	MCPPromptInfo,
	MCPServerState,
	MCPSettings,
	MCPGetServersResponse,
	MCPAddServerRequest,
	MCPAddServerResponse,
	MCPUpdateServerRequest,
	MCPUpdateServerResponse,
	MCPRemoveServerRequest,
	MCPRemoveServerResponse,
	MCPConnectServerRequest,
	MCPConnectServerResponse,
	MCPDisconnectServerRequest,
	MCPDisconnectServerResponse,
	MCPRefreshServerRequest,
	MCPRefreshServerResponse,
	MCPGetToolsResponse,
	MCPCallToolRequest,
	MCPCallToolResponse,
	MCPGetResourcesResponse,
	MCPReadResourceRequest,
	MCPReadResourceResponse,
	MCPGetPromptsResponse,
	MCPGetPromptRequest,
	MCPGetPromptResponse,
	MCPReadConfigFileRequest,
	MCPReadConfigFileResponse,
} from "./mcp.js";

// ACP types
export type {
	ACPConnectionStatus,
	ACPPermissionMode,
	ACPAgentConfig,
	ACPAgentState,
	ACPSettings,
	ACPGetAgentsResponse,
	ACPAddAgentRequest,
	ACPAddAgentResponse,
	ACPUpdateAgentRequest,
	ACPUpdateAgentResponse,
	ACPRemoveAgentRequest,
	ACPRemoveAgentResponse,
	ACPConnectAgentRequest,
	ACPConnectAgentResponse,
	ACPDisconnectAgentRequest,
	ACPDisconnectAgentResponse,
	ACPRefreshAgentRequest,
	ACPRefreshAgentResponse,
	ACPCancelSessionRequest,
	ACPCancelSessionResponse,
} from "./acp.js";

// OAuth types
export type {
	OAuthStartRequest,
	OAuthStartResponse,
	OAuthCallbackRequest,
	OAuthCallbackResponse,
	OAuthStatusRequest,
	OAuthStatusResponse,
	OAuthLogoutRequest,
	OAuthLogoutResponse,
	OAuthDevicePollRequest,
	OAuthDevicePollResponse,
} from "./oauth.js";

// Skills types
export type {
	SkillSource,
	SkillDefinition,
	SkillConditions,
	SkillReferenceSnapshot,
	SkillFile,
	SkillSettings,
	GetSkillsResponse,
	RefreshSkillsResponse,
	ReadSkillFileRequest,
	ReadSkillFileResponse,
	OpenSkillDirectoryRequest,
	OpenSkillDirectoryResponse,
	CreateSkillRequest,
	CreateSkillResponse,
	SkillDirectoryConfig,
	ListSkillDirectoriesResponse,
	AddSkillDirectoryRequest,
	AddSkillDirectoryResponse,
	UpdateSkillDirectoryRequest,
	UpdateSkillDirectoryResponse,
	RemoveSkillDirectoryRequest,
	RemoveSkillDirectoryResponse,
	SetSkillAgentRequest,
	SetSkillAgentResponse,
} from "./skills.js";

// Plugin types
export type {
	PluginCommandInfo,
	GetPluginCommandsResponse,
	ExecutePluginCommandRequest,
	ExecutePluginCommandResponse,
} from "./plugins.js";

// Memory panel types
export type {
	MemoryDiagnosticLevel,
	MemoryDiagnosticLogEntry,
	MemoryDiagnosticStatus,
	MemoryDiagnosticSubsystem,
	MemoryLogsCleanupResponse,
	MemoryLogsListRequest,
	MemoryLogsListResponse,
	MemoryLogsStatsResponse,
	MemoryManagedFileKind,
	MemoryManagedFile,
	MemoryRuntimeStatus,
	MemoryCapturePending,
	MemoryOverview,
	MemoryReadRequest,
	MemoryReadResponse,
	MemoryAppendRequest,
	MemoryAppendResponse,
	MemoryOverviewResponse,
	MemoryCaptureDecisionRequest,
	MemoryCaptureDecisionResponse,
	MemorySaveFileRequest,
	MemorySaveFileResponse,
} from "./memory.js";

// Scheduler types
export type {
	SchedulerRunReason,
	SchedulerTaskKind,
	SchedulerTaskSource,
	SchedulerRunStatus,
	SchedulerSchedule,
	SchedulerRunRecordDTO,
	SchedulerRunTimelineEntryDTO,
	SchedulerRunToolCallDTO,
	SchedulerRunStepDTO,
	SchedulerRunDetailDTO,
	SchedulerTaskSnapshotDTO,
	SchedulerUserTaskDTO,
	SchedulerListResponse,
	SchedulerGetRequest,
	SchedulerGetResponse,
	SchedulerRunNowRequest,
	SchedulerRunNowResponse,
	SchedulerSetEnabledRequest,
	SchedulerSetEnabledResponse,
	SchedulerCreateTaskRequest,
	SchedulerUpdateTaskRequest,
	SchedulerDeleteTaskRequest,
	SchedulerWriteTaskResponse,
	SchedulerDeleteTaskResponse,
	SchedulerListRunsRequest,
	SchedulerListRunsResponse,
	SchedulerGetRunRequest,
	SchedulerGetRunResponse,
} from "./scheduler.js";

// Settings types
export type {
	ColorTheme,
	MessageListDensity,
	TypographyDensity,
	BaseTheme,
	KeyboardShortcut,
	ShortcutSettings,
	EditorSettings,
	SoulMemoryLogLevel,
	SoulMemoryLoggingSettings,
	SoulMemoryCaptureSettings,
	SoulMemoryReviewSettings,
	SoulMemoryReadSettings,
	SoulMemorySettings,
	GeneralSettings,
	ChatSettings,
	NetworkSettings,
	ProxySettings,
	WechatChannelSettings,
	ChannelSettings,
	EvalsSettings,
	ShellMode,
	UISettings,
	AppSettings,
	GetSettingsResponse,
	SaveSettingsRequest,
	SaveSettingsResponse,
	TestProxyRequest,
	TestProxyResponse,
} from "./settings.js";

export type {
	GatewayChannelId,
	GatewayWechatLoginStatus,
	GatewayWechatStatus,
	GatewayWechatAccountStatus,
	GatewayStatus,
	GatewayGetStatusResponse,
	GatewayStartRequest,
	GatewayStartResponse,
	GatewayStopResponse,
	GatewayWechatAddAccountRequest,
	GatewayWechatAddAccountResponse,
	GatewayWechatStopAccountRequest,
	GatewayWechatStopAccountResponse,
	GatewayWechatRemoveAccountRequest,
	GatewayWechatRemoveAccountResponse,
	GatewayWechatRenameAccountRequest,
	GatewayWechatRenameAccountResponse,
	GatewayWechatLogoutRequest,
	GatewayWechatLogoutResponse,
} from "./gateway.js";

// Theme types
export type {
	ColorValue,
	ThemeDefs,
	ThemeBgColors,
	ThemeTextColors,
	ThemeBorderColors,
	ThemeShadows,
	ThemeEffects,
	ThemeNeutralColors,
	SemanticHighlightToken,
	HighlightFontStyle,
	HighlightStyle,
	HighlightLink,
	ThemeHighlightGroup,
	ThemeHighlights,
	SemanticUIToken,
	UIStyle,
	UILink,
	ThemeUIGroup,
	ThemeUITokens,
	ThemeColors,
	Theme,
	ThemeMeta,
	Base46Base30,
	Base46Base16,
	Base46Theme,
	GetThemesResponse,
	GetThemeResponse,
	ApplyThemeResponse,
	RefreshThemesResponse,
} from "./themes.js";

// Permission types
export type {
	PermissionInfo,
	PermissionResponse,
	PermissionRespondRequest,
} from "./permissions.js";

// Variable types
export type {
	VariablesListRequest,
	VariablesListResponse,
	VariablesSetRequest,
	VariablesSetResponse,
	VariablesDeleteRequest,
	VariablesDeleteResponse,
} from "./variables.js";

// Session goal types
export type {
	SessionGoal,
	SessionGoalStatus,
	GoalGetRequest,
	GoalGetResponse,
	GoalSetAction,
	GoalSetRequest,
	GoalSetResponse,
	GoalFileDiff,
	GoalDiffsRequest,
	GoalDiffsResponse,
} from "./goal.js";

// Session TOC (table of contents) types
export type {
	SessionSegment,
	SessionSegmentFile,
	SessionSegmentKind,
	SessionSegmentOrigin,
	SessionSegmentOutcome,
	GetSessionSegmentsResponse,
} from "./toc.js";

// Project directories types
export type {
	ProjectDirSummary,
	ProjectDirRecord,
	ProjectDirsListResponse,
	ProjectDirsGetRequest,
	ProjectDirsGetResponse,
	ProjectDirsAddRequest,
	ProjectDirsAddResponse,
	ProjectDirsUpdateRequest,
	ProjectDirsUpdateResponse,
	ProjectDirsRemoveRequest,
	ProjectDirsRemoveResponse,
} from "./project-dirs.js";

// UIMessage types
export type {
	ToolUIState,
	TextUIPart,
	ReasoningUIPart,
	FileUIPart,
	ToolUIPart,
	StepStartUIPart,
	StepsDataUIPart,
	ErrorDataUIPart,
	UIMessagePart,
	StepUIPart,
	ErrorUIPart,
	MessageMetadata,
	UIMessage,
	UIMessageChunk,
	UIMessagePartChunk,
	TokenUsage,
	SessionTokenUsage,
	UIMessageFinishChunk,
	UIMessageStreamData,
} from "./ui-message.js";

export {
	isTextUIPart,
	isReasoningUIPart,
	isToolUIPart,
	isFileUIPart,
	isStepUIPart,
	isErrorUIPart,
	getToolName,
} from "./ui-message.js";

// Search types
export {
	SEARCH_CATEGORIES,
	isSearchCategory,
} from "./search.js";

export type {
	SearchCategory,
	SearchRequest,
	SearchResult,
	SearchResponse,
	SearchWindowGuideState,
	SearchWindowSplitIntent,
	SearchWindowIntent,
	SearchWindowOpenOptions,
	SearchWindowShownPayload,
	SearchWindowAnchor,
} from "./search.js";

// User prompt snippet types
export type {
	UserPrompt,
	PromptReferenceSnapshot,
	PromptListResponse,
	PromptGetRequest,
	PromptGetResponse,
	PromptCreateRequest,
	PromptCreateResponse,
	PromptUpdateRequest,
	PromptUpdateResponse,
	PromptDeleteRequest,
	PromptDeleteResponse,
} from "./prompts.js";

// Todo / plan panel types
export type {
	TodoPlanScope,
	TodoPlanActivationMode,
	TodoPlanAutonomyMode,
	TodoPlanWindowActionRequest,
	TodoPlanDocument,
	TodoPlanContext,
	TodoPlanSnapshot,
	TodoPlanSettings,
	TodoPlanGetRequest,
	TodoPlanGetResponse,
	TodoPlanCreateRequest,
	TodoPlanCreateResponse,
	TodoPlanUpdateRequest,
	TodoPlanUpdateResponse,
	TodoPlanRenameRequest,
	TodoPlanRenameResponse,
	TodoPlanDeleteRequest,
	TodoPlanDeleteResponse,
	TodoPlanChangedPayload,
} from "./todo-plan.js";

// Evals types
export type {
	EvalsRecordDownvoteRequest,
	EvalsRecordDownvoteResponse,
	TurnEvalRecord,
	EvalsListRecordsRequest,
	EvalsListRecordsResponse,
	TurnEvalRecordView,
	EvalsListFixturesResponse,
	EvalFixtureMeta,
	EvalsReadFixtureRequest,
	EvalsReadFixtureResponse,
	EvalsListResultsResponse,
	EvalRunResultEntry,
	EvalsListCasesResponse,
	EvalCaseMeta,
	EvalsGetCaseRequest,
	EvalsGetCaseResponse,
	EvalsRunStartRequest,
	EvalsRunStartResponse,
	EvalsRunCancelResponse,
	EvalsRunProgressEvent,
	EvalsPromoteFixtureRequest,
	EvalsPromoteFixtureResponse,
	EvalsRetireCaseRequest,
	EvalsRetireCaseResponse,
	EvalsGenerateTriageRequest,
	EvalsGenerateTriageResponse,
	EvalsReadRunDetailRequest,
	EvalsReadRunDetailResponse,
	EvalRunCaseAttempt,
	EvalRunCaseDetail,
	EvalRunDetail,
	EvalsReadSnapshotRequest,
	EvalsReadSnapshotResponse,
	PromptSnapshotView,
	ContextSnapshotMessage,
	EvalsIncidentMetaDTO,
	EvalsIncidentListResponse,
	EvalsIncidentGetRequest,
	EvalsIncidentGetResponse,
	EvalsIncidentRunSummary,
	EvalsIncidentUpdateRequest,
	EvalsIncidentUpdateResponse,
	EvalsIncidentReadFileRequest,
	EvalsIncidentReadFileResponse,
	EvalsReplayStartRequest,
	EvalsReplayStartResponse,
	EvalsReplayProgressEvent,
	EvalsIncidentAnalyzeRequest,
	EvalsIncidentAnalyzeResponse,
	EvalsIncidentPromoteRequest,
	EvalsIncidentPromoteResponse,
	EvalsDiagnoseStartRequest,
	EvalsDiagnoseStartResponse,
	EvalsDiagnoseProgressEvent,
	EvalsRoundListRequest,
	EvalsRoundView,
	EvalsRoundListResponse,
	EvalsRoundReplayRequest,
	EvalsRoundReplayResponse,
} from "./evals.js";

export type {
	GetSessionUsageRequest,
	GetSessionUsageResponse,
	GetUsageSummaryRequest,
	GetUsageSummaryResponse,
	OnethingUsageBreakdownEntry,
	OnethingUsageBucket,
	OnethingUsageSummaryGranularity,
} from "./usage.js";

export type {
	PracticeConfig,
	PracticeConfigResponse,
	PracticeEventPayload,
	PracticeLedgerRecord,
	PracticeLogRequest,
	PracticeLogResponse,
	PracticePhaseEdge,
	PracticeRecentRequest,
	PracticeRecentResponse,
	PracticeSetConfigRequest,
	PracticeSnapshot,
	PracticeStartRequest,
	PracticeStateResponse,
	PracticeStopRequest,
	PracticeSummaryGranularity,
	PracticeSummaryRequest,
	PracticeSummaryResult,
} from "./practice.js";

export type {
	NotifyActivateEvent,
	NotifySimpleResponse,
	SetBadgeRequest,
	ShowNotificationRequest,
} from "./notify.js";

export type {
	TerminalAckPayload,
	TerminalAttachRequest,
	TerminalAttachResponse,
	TerminalCreateRequest,
	TerminalCreateResponse,
	TerminalDataEvent,
	TerminalExitEvent,
	TerminalInfo,
	TerminalKillRequest,
	TerminalListResponse,
	TerminalOutputChunk,
	TerminalResizeRequest,
	TerminalSimpleResponse,
	TerminalWriteRequest,
} from "./terminal.js";

export type {
	BrowserCreateTabRequest,
	BrowserCreateTabResponse,
	BrowserHydrateResponse,
	BrowserNavigateRequest,
	BrowserSetBoundsRequest,
	BrowserSetVisibleRequest,
	BrowserSimpleResponse,
	BrowserAddProfileRequest,
	BrowserPickResponse,
	BrowserProfile,
	BrowserProfileIdRequest,
	BrowserProfilesResponse,
	BrowserSearchEngine,
	BrowserSearchEngineId,
	BrowserSearchEngineResponse,
	BrowserSetSearchEngineRequest,
	BrowserTabIdRequest,
	BrowserTabInfo,
	BrowserTabsChangedEvent,
	BrowserViewBounds,
	PickedWebElement,
} from "./browser.js";

export {
	BROWSER_SEARCH_ENGINES,
	DEFAULT_BROWSER_SEARCH_ENGINE_ID,
	isBrowserSearchInput,
	resolveBrowserOmniboxInput,
	resolveBrowserSearchEngine,
} from "./browser.js";
