import { resolve } from 'path'
import { defineConfig, externalizeDepsPlugin } from 'electron-vite'
import vue from '@vitejs/plugin-vue'

const onethingPackageAliases = [
  { find: '@onething/core/agent-loop', replacement: resolve(__dirname, 'packages/core/agent-loop/index.ts') },
  // Browser-safe leaf module (no node deps) — must be registered BEFORE the
  // engine barrel so the renderer never drags node:crypto into the bundle.
  { find: '@onething/core/engine/attachment-mime', replacement: resolve(__dirname, 'packages/core/engine/attachment-mime.ts') },
  { find: '@onething/core/engine/streaming-args', replacement: resolve(__dirname, 'packages/core/engine/streaming-args.ts') },
  { find: '@onething/core/engine', replacement: resolve(__dirname, 'packages/core/engine/index.ts') },
  { find: '@onething/core/events', replacement: resolve(__dirname, 'packages/core/events/index.ts') },
  { find: '@onething/core/gateway-runtime', replacement: resolve(__dirname, 'packages/core/gateway-runtime.ts') },
  { find: '@onething/core/http', replacement: resolve(__dirname, 'packages/core/http/index.ts') },
  { find: '@onething/core/ipc', replacement: resolve(__dirname, 'packages/core/ipc/index.ts') },
  { find: '@onething/core/json', replacement: resolve(__dirname, 'packages/core/json.ts') },
  { find: '@onething/core/mcp', replacement: resolve(__dirname, 'packages/core/mcp/index.ts') },
  { find: '@onething/core/permission', replacement: resolve(__dirname, 'packages/core/permission/index.ts') },
  { find: '@onething/core/plugins', replacement: resolve(__dirname, 'packages/core/plugins/index.ts') },
  { find: '@onething/core/session/storage', replacement: resolve(__dirname, 'packages/core/session/storage/index.ts') },
  { find: '@onething/core/session', replacement: resolve(__dirname, 'packages/core/session/index.ts') },
  { find: '@onething/core/slash-commands', replacement: resolve(__dirname, 'packages/core/slash-commands.ts') },
  { find: '@onething/core/storage', replacement: resolve(__dirname, 'packages/core/storage/index.ts') },
  { find: '@onething/core/tools', replacement: resolve(__dirname, 'packages/core/tools/index.ts') },
  { find: '@onething/core', replacement: resolve(__dirname, 'packages/core/index.ts') },
  { find: '@onething/gateway/config', replacement: resolve(__dirname, 'packages/gateway/src/config.ts') },
  { find: '@onething/gateway/core', replacement: resolve(__dirname, 'packages/gateway/src/core/index.ts') },
  { find: '@onething/gateway/telegram', replacement: resolve(__dirname, 'packages/gateway/src/channels/telegram/index.ts') },
  { find: '@onething/gateway/wechat', replacement: resolve(__dirname, 'packages/gateway/src/channels/wechat/index.ts') },
  { find: '@onething/gateway', replacement: resolve(__dirname, 'packages/gateway/src/index.ts') },
  { find: '@onething/electron-host/accessibility/permissions', replacement: resolve(__dirname, 'apps/electron/src/accessibility/permissions.ts') },
  { find: '@onething/electron-host/app/activate', replacement: resolve(__dirname, 'apps/electron/src/app/activate.ts') },
  { find: '@onething/electron-host/app/before-quit', replacement: resolve(__dirname, 'apps/electron/src/app/before-quit.ts') },
  { find: '@onething/electron-host/app/bootstrap', replacement: resolve(__dirname, 'apps/electron/src/app/bootstrap.ts') },
  { find: '@onething/electron-host/app/did-become-active', replacement: resolve(__dirname, 'apps/electron/src/app/did-become-active.ts') },
  { find: '@onething/electron-host/app/login-shell-env', replacement: resolve(__dirname, 'apps/electron/src/app/login-shell-env.ts') },
  { find: '@onething/electron-host/app/main-process', replacement: resolve(__dirname, 'apps/electron/src/app/main-process.ts') },
  { find: '@onething/electron-host/app/ready', replacement: resolve(__dirname, 'apps/electron/src/app/ready.ts') },
  { find: '@onething/electron-host/app/window-all-closed', replacement: resolve(__dirname, 'apps/electron/src/app/window-all-closed.ts') },
  { find: '@onething/electron-host/auth/auth-fetch', replacement: resolve(__dirname, 'apps/electron/src/auth/auth-fetch.ts') },
  { find: '@onething/electron-host/auth/electron-auth', replacement: resolve(__dirname, 'apps/electron/src/auth/electron-auth.ts') },
  { find: '@onething/electron-host/auth/token-store', replacement: resolve(__dirname, 'apps/electron/src/auth/token-store.ts') },
  { find: '@onething/electron-host/gateway/lifecycle', replacement: resolve(__dirname, 'apps/electron/src/gateway/lifecycle.ts') },
  { find: '@onething/electron-host/ipc/acp', replacement: resolve(__dirname, 'apps/electron/src/ipc/acp.ts') },
  { find: '@onething/electron-host/ipc/agents', replacement: resolve(__dirname, 'apps/electron/src/ipc/agents.ts') },
  { find: '@onething/electron-host/ipc/app-state', replacement: resolve(__dirname, 'apps/electron/src/ipc/app-state.ts') },
  { find: '@onething/electron-host/ipc/chat', replacement: resolve(__dirname, 'apps/electron/src/ipc/chat.ts') },
  { find: '@onething/electron-host/ipc/files', replacement: resolve(__dirname, 'apps/electron/src/ipc/files.ts') },
  { find: '@onething/electron-host/ipc/gateway', replacement: resolve(__dirname, 'apps/electron/src/ipc/gateway.ts') },
  { find: '@onething/electron-host/ipc/markdown', replacement: resolve(__dirname, 'apps/electron/src/ipc/markdown.ts') },
  { find: '@onething/electron-host/ipc/media', replacement: resolve(__dirname, 'apps/electron/src/ipc/media.ts') },
  { find: '@onething/electron-host/ipc/memory', replacement: resolve(__dirname, 'apps/electron/src/ipc/memory.ts') },
  { find: '@onething/electron-host/ipc/mcp', replacement: resolve(__dirname, 'apps/electron/src/ipc/mcp.ts') },
  { find: '@onething/electron-host/ipc/models', replacement: resolve(__dirname, 'apps/electron/src/ipc/models.ts') },
  { find: '@onething/electron-host/ipc/oauth', replacement: resolve(__dirname, 'apps/electron/src/ipc/oauth.ts') },
  { find: '@onething/electron-host/ipc/permission', replacement: resolve(__dirname, 'apps/electron/src/ipc/permission.ts') },
  { find: '@onething/electron-host/ipc/plugins', replacement: resolve(__dirname, 'apps/electron/src/ipc/plugins.ts') },
  { find: '@onething/electron-host/ipc/prompts', replacement: resolve(__dirname, 'apps/electron/src/ipc/prompts.ts') },
  { find: '@onething/electron-host/ipc/providers', replacement: resolve(__dirname, 'apps/electron/src/ipc/providers.ts') },
  { find: '@onething/electron-host/ipc/project-dirs', replacement: resolve(__dirname, 'apps/electron/src/ipc/project-dirs.ts') },
  { find: '@onething/electron-host/ipc/scheduler', replacement: resolve(__dirname, 'apps/electron/src/ipc/scheduler.ts') },
  { find: '@onething/electron-host/ipc/shell', replacement: resolve(__dirname, 'apps/electron/src/ipc/shell.ts') },
  { find: '@onething/electron-host/ipc/session-command', replacement: resolve(__dirname, 'apps/electron/src/ipc/session-command.ts') },
  { find: '@onething/electron-host/ipc/sessions', replacement: resolve(__dirname, 'apps/electron/src/ipc/sessions.ts') },
  { find: '@onething/electron-host/ipc/skills', replacement: resolve(__dirname, 'apps/electron/src/ipc/skills.ts') },
  { find: '@onething/electron-host/ipc/themes', replacement: resolve(__dirname, 'apps/electron/src/ipc/themes.ts') },
  { find: '@onething/electron-host/ipc/todo-plan', replacement: resolve(__dirname, 'apps/electron/src/ipc/todo-plan.ts') },
  { find: '@onething/electron-host/ipc/tools', replacement: resolve(__dirname, 'apps/electron/src/ipc/tools.ts') },
  { find: '@onething/electron-host/ipc/window', replacement: resolve(__dirname, 'apps/electron/src/ipc/window.ts') },
  { find: '@onething/electron-host/ipc/variables', replacement: resolve(__dirname, 'apps/electron/src/ipc/variables.ts') },
  { find: '@onething/electron-host/logging/console-capture', replacement: resolve(__dirname, 'apps/electron/src/logging/console-capture.ts') },
  { find: '@onething/electron-host/menu/application-menu', replacement: resolve(__dirname, 'apps/electron/src/menu/application-menu.ts') },
  { find: '@onething/electron-host/web-preview/web-preview', replacement: resolve(__dirname, 'apps/electron/src/web-preview/web-preview.ts') },
  { find: '@onething/electron-host/media/protocol', replacement: resolve(__dirname, 'apps/electron/src/media/protocol.ts') },
  { find: '@onething/electron-host/network/proxy', replacement: resolve(__dirname, 'apps/electron/src/network/proxy.ts') },
  { find: '@onething/electron-host/oauth/events', replacement: resolve(__dirname, 'apps/electron/src/oauth/events.ts') },
  { find: '@onething/electron-host/power/resume', replacement: resolve(__dirname, 'apps/electron/src/power/resume.ts') },
  { find: '@onething/electron-host/search/ipc', replacement: resolve(__dirname, 'apps/electron/src/search/ipc.ts') },
  { find: '@onething/electron-host/search/window-actions', replacement: resolve(__dirname, 'apps/electron/src/search/window-actions.ts') },
  { find: '@onething/electron-host/search/window-controller', replacement: resolve(__dirname, 'apps/electron/src/search/window-controller.ts') },
  { find: '@onething/electron-host/search/window', replacement: resolve(__dirname, 'apps/electron/src/search/window.ts') },
  { find: '@onething/electron-host/settings/ipc-host', replacement: resolve(__dirname, 'apps/electron/src/settings/ipc-host.ts') },
  { find: '@onething/electron-host/shell/operations', replacement: resolve(__dirname, 'apps/electron/src/shell/operations.ts') },
  { find: '@onething/electron-host/skills/environment', replacement: resolve(__dirname, 'apps/electron/src/skills/environment.ts') },
  { find: '@onething/electron-host/shortcuts/global-shortcuts', replacement: resolve(__dirname, 'apps/electron/src/shortcuts/global-shortcuts.ts') },
  { find: '@onething/electron-host/todo-plan/notifications', replacement: resolve(__dirname, 'apps/electron/src/todo-plan/notifications.ts') },
  { find: '@onething/electron-host/music/ipc', replacement: resolve(__dirname, 'apps/electron/src/music/ipc.ts') },
  { find: '@onething/electron-host/music/pty-host', replacement: resolve(__dirname, 'apps/electron/src/music/pty-host.ts') },
  { find: '@onething/electron-host/voice/events', replacement: resolve(__dirname, 'apps/electron/src/voice/events.ts') },
  { find: '@onething/electron-host/voice/ipc', replacement: resolve(__dirname, 'apps/electron/src/voice/ipc.ts') },
  { find: '@onething/electron-host/voice/runtime-window', replacement: resolve(__dirname, 'apps/electron/src/voice/runtime-window.ts') },
  { find: '@onething/electron-host/voice/tray', replacement: resolve(__dirname, 'apps/electron/src/voice/tray.ts') },
  { find: '@onething/electron-host/window/activation', replacement: resolve(__dirname, 'apps/electron/src/window/activation.ts') },
  { find: '@onething/electron-host/window/external-links', replacement: resolve(__dirname, 'apps/electron/src/window/external-links.ts') },
  { find: '@onething/electron-host/window/image-preview-window', replacement: resolve(__dirname, 'apps/electron/src/window/image-preview-window.ts') },
  { find: '@onething/electron-host/window/macos-panel', replacement: resolve(__dirname, 'apps/electron/src/window/macos-panel.ts') },
  { find: '@onething/electron-host/window/main-window', replacement: resolve(__dirname, 'apps/electron/src/window/main-window.ts') },
  { find: '@onething/electron-host/window/main-window-recovery', replacement: resolve(__dirname, 'apps/electron/src/window/main-window-recovery.ts') },
  { find: '@onething/electron-host/window/renderer-targets', replacement: resolve(__dirname, 'apps/electron/src/window/renderer-targets.ts') },
  { find: '@onething/electron-host/window/search-window', replacement: resolve(__dirname, 'apps/electron/src/window/search-window.ts') },
  { find: '@onething/electron-host/window/search-window-layout', replacement: resolve(__dirname, 'apps/electron/src/window/search-window-layout.ts') },
  { find: '@onething/electron-host/window/settings-window', replacement: resolve(__dirname, 'apps/electron/src/window/settings-window.ts') },
  { find: '@onething/electron-host/window/session-security', replacement: resolve(__dirname, 'apps/electron/src/window/session-security.ts') },
  { find: '@onething/electron-host/window/todo-plan-presentation', replacement: resolve(__dirname, 'apps/electron/src/window/todo-plan-presentation.ts') },
  { find: '@onething/electron-host/window/todo-plan-window', replacement: resolve(__dirname, 'apps/electron/src/window/todo-plan-window.ts') },
  { find: '@onething/electron-host/window/types', replacement: resolve(__dirname, 'apps/electron/src/window/types.ts') },
  { find: '@onething/electron-host/window/window-visibility', replacement: resolve(__dirname, 'apps/electron/src/window/window-visibility.ts') },
  { find: '@onething/electron-host/window/window-state', replacement: resolve(__dirname, 'apps/electron/src/window/window-state.ts') },
  { find: '@onething/electron-host/window', replacement: resolve(__dirname, 'apps/electron/src/window/index.ts') },
  { find: '@onething/runtime/headless', replacement: resolve(__dirname, 'packages/onething-runtime/src/headless/index.ts') },
  { find: '@onething/runtime/runtime', replacement: resolve(__dirname, 'packages/onething-runtime/src/runtime.ts') },
  { find: '@onething/runtime/product-stream-runtime', replacement: resolve(__dirname, 'packages/onething-runtime/src/product-stream-runtime.ts') },
  { find: '@onething/runtime/auth', replacement: resolve(__dirname, 'packages/onething-runtime/src/auth/index.ts') },
  { find: '@onething/runtime/agent-loop/providers', replacement: resolve(__dirname, 'packages/onething-runtime/src/agent-loop/providers/index.ts') },
  { find: '@onething/runtime/agent-loop', replacement: resolve(__dirname, 'packages/onething-runtime/src/agent-loop/index.ts') },
  { find: '@onething/runtime/stream-runtime', replacement: resolve(__dirname, 'packages/onething-runtime/src/stream-runtime.ts') },
  { find: '@onething/runtime/stream-engine', replacement: resolve(__dirname, 'packages/onething-runtime/src/stream-engine.ts') },
  { find: '@onething/runtime/stream-processor', replacement: resolve(__dirname, 'packages/onething-runtime/src/stream-processor.ts') },
  { find: '@onething/runtime/gateway', replacement: resolve(__dirname, 'packages/onething-runtime/src/gateway-runtime.ts') },
  { find: '@onething/runtime/acp', replacement: resolve(__dirname, 'packages/onething-runtime/src/acp/index.ts') },
  { find: '@onething/runtime/external-agents', replacement: resolve(__dirname, 'packages/onething-runtime/src/external-agents/index.ts') },
  { find: '@onething/runtime/agents', replacement: resolve(__dirname, 'packages/onething-runtime/src/agents/index.ts') },
  { find: '@onething/runtime/files/ripgrep', replacement: resolve(__dirname, 'packages/onething-runtime/src/files/ripgrep.ts') },
  { find: '@onething/runtime/files', replacement: resolve(__dirname, 'packages/onething-runtime/src/files/index.ts') },
  { find: '@onething/runtime/mcp', replacement: resolve(__dirname, 'packages/onething-runtime/src/mcp/index.ts') },
  { find: '@onething/runtime/scheduler', replacement: resolve(__dirname, 'packages/onething-runtime/src/scheduler/index.ts') },
  { find: '@onething/runtime/search/protocol', replacement: resolve(__dirname, 'packages/onething-runtime/src/search/protocol.ts') },
  { find: '@onething/runtime/search', replacement: resolve(__dirname, 'packages/onething-runtime/src/search/index.ts') },
  { find: '@onething/runtime/voice/kws/text2token', replacement: resolve(__dirname, 'packages/onething-runtime/src/voice/kws/text2token.ts') },
  { find: '@onething/runtime/voice/volcano/protocol', replacement: resolve(__dirname, 'packages/onething-runtime/src/voice/volcano/protocol.ts') },
  { find: '@onething/runtime/voice/volcano/asr-session', replacement: resolve(__dirname, 'packages/onething-runtime/src/voice/volcano/asr-session.ts') },
  { find: '@onething/runtime/voice/volcano/tts-session', replacement: resolve(__dirname, 'packages/onething-runtime/src/voice/volcano/tts-session.ts') },
  { find: '@onething/runtime/voice/providers', replacement: resolve(__dirname, 'packages/onething-runtime/src/voice/providers.ts') },
  { find: '@onething/runtime/voice/text', replacement: resolve(__dirname, 'packages/onething-runtime/src/voice/text.ts') },
  { find: '@onething/runtime/voice', replacement: resolve(__dirname, 'packages/onething-runtime/src/voice/index.ts') },
  { find: '@onething/runtime/providers/model-capability', replacement: resolve(__dirname, 'packages/onething-runtime/src/providers/model-capability.ts') },
  { find: '@onething/runtime/providers/provider-config', replacement: resolve(__dirname, 'packages/onething-runtime/src/providers/provider-config.ts') },
  { find: '@onething/runtime/project-dirs/id', replacement: resolve(__dirname, 'packages/onething-runtime/src/project-dirs/id.ts') },
  { find: '@onething/runtime/project-dirs/persistence', replacement: resolve(__dirname, 'packages/onething-runtime/src/project-dirs/persistence.ts') },
  { find: '@onething/runtime/project-dirs/prompt', replacement: resolve(__dirname, 'packages/onething-runtime/src/project-dirs/prompt.ts') },
  { find: '@onething/runtime/project-dirs/store', replacement: resolve(__dirname, 'packages/onething-runtime/src/project-dirs/store.ts') },
  { find: '@onething/runtime/project-dirs', replacement: resolve(__dirname, 'packages/onething-runtime/src/project-dirs/index.ts') },
  { find: '@onething/runtime/prompts', replacement: resolve(__dirname, 'packages/onething-runtime/src/prompts/index.ts') },
  { find: '@onething/runtime/providers', replacement: resolve(__dirname, 'packages/onething-runtime/src/providers/index.ts') },
  { find: '@onething/runtime/skills', replacement: resolve(__dirname, 'packages/onething-runtime/src/skills/index.ts') },
  { find: '@onething/runtime/goals', replacement: resolve(__dirname, 'packages/onething-runtime/src/goals/index.ts') },
  { find: '@onething/runtime/usage', replacement: resolve(__dirname, 'packages/onething-runtime/src/usage/index.ts') },
  { find: '@onething/runtime/toc', replacement: resolve(__dirname, 'packages/onething-runtime/src/toc/index.ts') },
  { find: '@onething/runtime/practice', replacement: resolve(__dirname, 'packages/onething-runtime/src/practice/index.ts') },
  { find: '@onething/runtime/media', replacement: resolve(__dirname, 'packages/onething-runtime/src/media/index.ts') },
  { find: '@onething/runtime/memory/active-memory', replacement: resolve(__dirname, 'packages/onething-runtime/src/memory/active-memory.ts') },
  { find: '@onething/runtime/memory/append', replacement: resolve(__dirname, 'packages/onething-runtime/src/memory/append.ts') },
  { find: '@onething/runtime/memory/capture-actions', replacement: resolve(__dirname, 'packages/onething-runtime/src/memory/capture-actions.ts') },
  { find: '@onething/runtime/memory/canonical', replacement: resolve(__dirname, 'packages/onething-runtime/src/memory/canonical.ts') },
  { find: '@onething/runtime/memory/database', replacement: resolve(__dirname, 'packages/onething-runtime/src/memory/database.ts') },
  { find: '@onething/runtime/memory/daily-context', replacement: resolve(__dirname, 'packages/onething-runtime/src/memory/daily-context.ts') },
  { find: '@onething/runtime/memory/diagnostics-logger', replacement: resolve(__dirname, 'packages/onething-runtime/src/memory/diagnostics-logger.ts') },
  { find: '@onething/runtime/memory/dreaming', replacement: resolve(__dirname, 'packages/onething-runtime/src/memory/dreaming.ts') },
  { find: '@onething/runtime/memory/flush', replacement: resolve(__dirname, 'packages/onething-runtime/src/memory/flush.ts') },
  { find: '@onething/runtime/memory/graph', replacement: resolve(__dirname, 'packages/onething-runtime/src/memory/graph.ts') },
  { find: '@onething/runtime/memory/hermes-file-memory', replacement: resolve(__dirname, 'packages/onething-runtime/src/memory/hermes-file-memory.ts') },
  { find: '@onething/runtime/memory/indexer', replacement: resolve(__dirname, 'packages/onething-runtime/src/memory/indexer.ts') },
  { find: '@onething/runtime/memory/ipc', replacement: resolve(__dirname, 'packages/onething-runtime/src/memory/ipc.ts') },
  { find: '@onething/runtime/memory/managed-files', replacement: resolve(__dirname, 'packages/onething-runtime/src/memory/managed-files.ts') },
  { find: '@onething/runtime/memory/prompt-context', replacement: resolve(__dirname, 'packages/onething-runtime/src/memory/prompt-context.ts') },
  { find: '@onething/runtime/memory/review', replacement: resolve(__dirname, 'packages/onething-runtime/src/memory/review.ts') },
  { find: '@onething/runtime/memory/search', replacement: resolve(__dirname, 'packages/onething-runtime/src/memory/search.ts') },
  { find: '@onething/runtime/memory/types', replacement: resolve(__dirname, 'packages/onething-runtime/src/memory/types.ts') },
  { find: '@onething/runtime/memory/workspace', replacement: resolve(__dirname, 'packages/onething-runtime/src/memory/workspace.ts') },
  { find: '@onething/runtime/memory', replacement: resolve(__dirname, 'packages/onething-runtime/src/memory/index.ts') },
  { find: '@onething/runtime/music', replacement: resolve(__dirname, 'packages/onething-runtime/src/music/index.ts') },
  { find: '@onething/runtime/markdown', replacement: resolve(__dirname, 'packages/onething-runtime/src/markdown/index.ts') },
  { find: '@onething/runtime/themes/base46-parser', replacement: resolve(__dirname, 'packages/onething-runtime/src/themes/base46-parser.ts') },
  { find: '@onething/runtime/themes/css-mapper', replacement: resolve(__dirname, 'packages/onething-runtime/src/themes/css-mapper.ts') },
  { find: '@onething/runtime/themes/resolver', replacement: resolve(__dirname, 'packages/onething-runtime/src/themes/resolver.ts') },
  { find: '@onething/runtime/themes/role-mapping', replacement: resolve(__dirname, 'packages/onething-runtime/src/themes/role-mapping.ts') },
  { find: '@onething/runtime/themes/theme-runtime', replacement: resolve(__dirname, 'packages/onething-runtime/src/themes/theme-runtime.ts') },
  { find: '@onething/runtime/themes', replacement: resolve(__dirname, 'packages/onething-runtime/src/themes/index.ts') },
  { find: '@onething/runtime/todo-plan', replacement: resolve(__dirname, 'packages/onething-runtime/src/todo-plan/index.ts') },
  { find: '@onething/runtime/variables/providers/background-jobs', replacement: resolve(__dirname, 'packages/onething-runtime/src/variables/providers/background-jobs.ts') },
  { find: '@onething/runtime/variables/providers/music-radio', replacement: resolve(__dirname, 'packages/onething-runtime/src/variables/providers/music-radio.ts') },
  { find: '@onething/runtime/variables/bootstrap', replacement: resolve(__dirname, 'packages/onething-runtime/src/variables/bootstrap.ts') },
  { find: '@onething/runtime/variables/providers/core', replacement: resolve(__dirname, 'packages/onething-runtime/src/variables/providers/core.ts') },
  { find: '@onething/runtime/variables/providers/datetime', replacement: resolve(__dirname, 'packages/onething-runtime/src/variables/providers/datetime.ts') },
  { find: '@onething/runtime/variables/providers/git-branch', replacement: resolve(__dirname, 'packages/onething-runtime/src/variables/providers/git-branch.ts') },
  { find: '@onething/runtime/variables/providers/global-store', replacement: resolve(__dirname, 'packages/onething-runtime/src/variables/providers/global-store.ts') },
  { find: '@onething/runtime/variables/providers/goal', replacement: resolve(__dirname, 'packages/onething-runtime/src/variables/providers/goal.ts') },
  { find: '@onething/runtime/variables/providers/notes', replacement: resolve(__dirname, 'packages/onething-runtime/src/variables/providers/notes.ts') },
  { find: '@onething/runtime/variables/providers/session-store', replacement: resolve(__dirname, 'packages/onething-runtime/src/variables/providers/session-store.ts') },
  { find: '@onething/runtime/variables/providers', replacement: resolve(__dirname, 'packages/onething-runtime/src/variables/providers/index.ts') },
  { find: '@onething/runtime/variables/schema', replacement: resolve(__dirname, 'packages/onething-runtime/src/variables/schema.ts') },
  { find: '@onething/runtime/variables/registry', replacement: resolve(__dirname, 'packages/onething-runtime/src/variables/registry.ts') },
  { find: '@onething/runtime/variables/format', replacement: resolve(__dirname, 'packages/onething-runtime/src/variables/format.ts') },
  { find: '@onething/runtime/variables/validation', replacement: resolve(__dirname, 'packages/onething-runtime/src/variables/validation.ts') },
  { find: '@onething/runtime/variables', replacement: resolve(__dirname, 'packages/onething-runtime/src/variables/index.ts') },
  { find: '@onething/runtime/triggers/skill-review', replacement: resolve(__dirname, 'packages/onething-runtime/src/triggers/skill-review.ts') },
  { find: '@onething/runtime/triggers/skill-review-state', replacement: resolve(__dirname, 'packages/onething-runtime/src/triggers/skill-review-state.ts') },
  { find: '@onething/runtime/triggers', replacement: resolve(__dirname, 'packages/onething-runtime/src/triggers/index.ts') },
  { find: '@onething/runtime/settings', replacement: resolve(__dirname, 'packages/onething-runtime/src/settings/index.ts') },
  { find: '@onething/runtime/sessions', replacement: resolve(__dirname, 'packages/onething-runtime/src/sessions/index.ts') },
  { find: '@onething/runtime/storage', replacement: resolve(__dirname, 'packages/onething-runtime/src/storage/index.ts') },
  { find: '@onething/runtime/permissions', replacement: resolve(__dirname, 'packages/onething-runtime/src/permissions/index.ts') },
  { find: '@onething/runtime/plugins', replacement: resolve(__dirname, 'packages/onething-runtime/src/plugins/index.ts') },
  { find: '@onething/runtime/tools/background-jobs', replacement: resolve(__dirname, 'packages/onething-runtime/src/tools/background-jobs.ts') },
  { find: '@onething/runtime/tools/bash-classifier', replacement: resolve(__dirname, 'packages/onething-runtime/src/tools/bash-classifier.ts') },
  { find: '@onething/runtime/tools/bash-executor', replacement: resolve(__dirname, 'packages/onething-runtime/src/tools/bash-executor.ts') },
  { find: '@onething/runtime/tools/edit-engine', replacement: resolve(__dirname, 'packages/onething-runtime/src/tools/edit-engine.ts') },
  { find: '@onething/runtime/tools/file-mutation-audit', replacement: resolve(__dirname, 'packages/onething-runtime/src/tools/file-mutation-audit.ts') },
  { find: '@onething/runtime/tools/file-mutation-queue', replacement: resolve(__dirname, 'packages/onething-runtime/src/tools/file-mutation-queue.ts') },
  { find: '@onething/runtime/tools/file-snapshot', replacement: resolve(__dirname, 'packages/onething-runtime/src/tools/file-snapshot.ts') },
  { find: '@onething/runtime/tools/builtin/calculator', replacement: resolve(__dirname, 'packages/onething-runtime/src/tools/builtin/calculator.ts') },
  { find: '@onething/runtime/tools/output-accumulator', replacement: resolve(__dirname, 'packages/onething-runtime/src/tools/output-accumulator.ts') },
  { find: '@onething/runtime/tools/replacers', replacement: resolve(__dirname, 'packages/onething-runtime/src/tools/replacers.ts') },
  { find: '@onething/runtime/tools/sandbox-runtime', replacement: resolve(__dirname, 'packages/onething-runtime/src/tools/sandbox-runtime.ts') },
  { find: '@onething/runtime/tools/sandbox', replacement: resolve(__dirname, 'packages/onething-runtime/src/tools/sandbox.ts') },
  { find: '@onething/runtime/tools/sensitive-files', replacement: resolve(__dirname, 'packages/onething-runtime/src/tools/sensitive-files.ts') },
  { find: '@onething/runtime/tools/text-truncation', replacement: resolve(__dirname, 'packages/onething-runtime/src/tools/text-truncation.ts') },
  { find: '@onething/runtime/tools', replacement: resolve(__dirname, 'packages/onething-runtime/src/tools/index.ts') },
  { find: '@onething/runtime/perf', replacement: resolve(__dirname, 'packages/onething-runtime/src/perf/index.ts') },
  { find: '@onething/runtime', replacement: resolve(__dirname, 'packages/onething-runtime/src/index.ts') },
]

export default defineConfig({
  main: {
    plugins: [externalizeDepsPlugin()],
    build: {
      rollupOptions: {
        input: {
          index: resolve(__dirname, 'apps/electron/src/main.ts'),
          cli: resolve(__dirname, 'apps/electron/src/main/cli/index.ts')
        }
      }
    },
    resolve: {
      alias: [
        ...onethingPackageAliases,
        { find: '@main', replacement: resolve(__dirname, 'apps/electron/src/main') },
        { find: '@shared', replacement: resolve(__dirname, 'packages/shared') }
      ]
    }
  },
  preload: {
    plugins: [externalizeDepsPlugin()],
    build: {
      rollupOptions: {
        input: {
          index: resolve(__dirname, 'apps/electron/src/preload.ts')
        },
        output: {
          format: 'cjs',
          entryFileNames: '[name].js'
        }
      }
    },
    resolve: {
      alias: [
        ...onethingPackageAliases,
        { find: '@shared', replacement: resolve(__dirname, 'packages/shared') }
      ]
    }
  },
  renderer: {
    root: '.',
    build: {
      rollupOptions: {
        input: {
          index: resolve(__dirname, 'index.html')
        }
      }
    },
    resolve: {
      alias: [
        ...onethingPackageAliases,
        { find: '@', replacement: resolve(__dirname, 'packages/renderer') },
        { find: '@renderer', replacement: resolve(__dirname, 'packages/renderer') },
        { find: '@shared', replacement: resolve(__dirname, 'packages/shared') }
      ]
    },
    plugins: [vue()],
    server: {
      host: '127.0.0.1',
      port: 5173
    }
  }
})
