/**
 * IPC Types Index
 * Unified export of all IPC-related type definitions
 *
 * This file aggregates and re-exports all types from the modular structure,
 * maintaining backward compatibility with existing imports from '../shared/ipc.js'
 */

// IPC Channel Constants
export { IPC_CHANNELS } from './channels.js'

export { DEFAULT_AGENT_ID } from './agents.js'
export type {
  AgentDefinition,
  AgentsListResponse,
  AgentCreateRequest,
  AgentCreateResponse,
  AgentUpdateRequest,
  AgentUpdateResponse,
  AgentDeleteRequest,
  AgentDeleteResponse,
} from './agents.js'

// IPC Router infrastructure
export { defineRouter, getChannelName } from './router.js'
export type { RouteConfig, DomainRoutes, Router, RouteHandlers, RouteAPI } from './router.js'

// Tool types
export type {
  GetToolsResponse,
  ExecuteToolRequest,
  ExecuteToolResponse,
  ToolParameter,
  ToolDefinition,
  ToolCall,
  ToolResultContentPart,
  ToolResult,
  ToolPartialResult,
  ToolExecutionMode,
  ToolRenderShell,
  ToolRenderKind,
  PermissionMode,
  BashToolSettings,
  ToolCallModelSettings,
  ToolSettings,
  StreamMessageChunk,
  SendMessageStreamResponse,
} from './tools.js'

// Chat types
export type {
  VoiceASRProvider,
  VoiceTTSProvider,
  VoiceEndpointingMode,
  VoiceRuntimeStatus,
  VoiceWakeSettings,
  VoiceVADSettings,
  VoiceASRSettings,
  VoiceTTSSettings,
  VoiceConversationSettings,
  VoiceSettings,
  VoiceTranscriptMetadata,
  VoiceLatencyMilestone,
  VoiceLatencyMilestoneName,
  VoiceRuntimeState,
  VoiceEvent,
  VoiceRuntimeEvent,
  VoiceRuntimeCommand,
  VoiceStartRequest,
  VoiceStopRequest,
  VoiceSubmitUtteranceRequest,
  VoiceSubmitTranscriptRequest,
  VoiceSynthesizeRequest,
  VoiceTestASRRequest,
  VoiceTestTTSRequest,
  VoiceTTSModel,
  VoiceBaseResponse,
  VoiceGetStateResponse,
  VoiceSubmitUtteranceResponse,
  VoiceSynthesizeResponse,
  VoiceTTSModelsResponse,
} from './voice.js'

export type {
  ContextVariable,
  VariableLevel,
  ContentPart,
  StepType,
  Step,
  AttachmentMediaType,
  MessageAttachment,
  ChatMessage,
  PromptContextRole,
  BaseInstructions,
  PromptContextMarker,
  PromptContextFragment,
  TurnContextSnapshot,
  PromptContextState,
  // Session-level optimization (Phase 4: Metadata Separation)
  SessionMeta,
  SessionDetails,
  ChatSession,
  SendMessageRequest,
  SendMessageResponse,
  EditAndResendRequest,
  EditAndResendResponse,
  GetChatHistoryRequest,
  GetChatHistoryResponse,
  GetSessionsResponse,
  CreateSessionRequest,
  CreateSessionResponse,
  SwitchSessionRequest,
  SwitchSessionResponse,
  DeleteSessionRequest,
  DeleteSessionResponse,
  RenameSessionRequest,
  RenameSessionResponse,
  CreateBranchRequest,
  CreateBranchResponse,
  UpdateSessionPinRequest,
  UpdateSessionPinResponse,
  GenerateTitleRequest,
  GenerateTitleResponse,
  SystemPromptToolSnapshot,
  SystemPromptSkillSnapshot,
  SystemPromptSnapshot,
  GetSystemPromptSnapshotRequest,
  GetSystemPromptSnapshotResponse,
  // Optimized session loading (Phase 4)
  GetSessionsListResponse,
  ActivateSessionResponse,
  GetSessionMessagesResponse,
  SessionMessagesPageDirection,
  SessionMessagesPageAnchor,
  GetSessionMessagesPageRequest,
  SessionMessagePageCursor,
  GetSessionMessagesPageResponse,
  UserMessageMarker,
  GetSessionUserMarkersResponse,
} from './chat.js'

// Media types
export type {
  MediaKind,
  MediaSource,
  MediaUsageTag,
  MediaAssetLink,
  MediaAssetMetadata,
  MediaAsset,
  MediaQuery,
  MediaGalleryResponse,
  MediaRebuildResponse,
} from './media.js'

// Markdown asset / attachment types
export type {
  MarkdownAssetKind,
  MarkdownAssetResolution,
  MarkdownResolveAssetRequest,
  MarkdownResolveAssetResponse,
  MarkdownAttachmentInput,
  SavedMarkdownAttachment,
  MarkdownSaveAttachmentsRequest,
  MarkdownSaveAttachmentsResponse,
} from './markdown.js'

// Provider types
export type {
  AIProviderId,
  ThinkingEffort,
  OAuthFlowType,
  OAuthToken,
  OpenRouterModel,
  ProviderInfo,
  ProviderConfig,
  ModelCapabilityOverride,
  CustomProviderConfig,
  AISettings,
  ModelCapabilityEntry,
  ModelType,
  ModelInfo,
  GetProvidersResponse,
  CodexUsageWindow,
  CodexUsageCredits,
  CodexUsageLimit,
  CodexProviderUsage,
  ProviderUsageRequest,
  ProviderUsageResponse,
  ProviderEnvVarCandidate,
  ProviderEnvStatus,
  GetProviderEnvStatusRequest,
  GetProviderEnvStatusResponse,
} from './providers.js'

export { AIProvider } from './providers.js'

// MCP types
export type {
  MCPTransportType,
  MCPServerConfig,
  MCPConnectionStatus,
  MCPToolInfo,
  MCPResourceInfo,
  MCPPromptInfo,
  MCPServerState,
  MCPSettings,
  MCPGetServersResponse,
  MCPAddServerRequest,
  MCPAddServerResponse,
  MCPUpdateServerRequest,
  MCPUpdateServerResponse,
  MCPRemoveServerRequest,
  MCPRemoveServerResponse,
  MCPConnectServerRequest,
  MCPConnectServerResponse,
  MCPDisconnectServerRequest,
  MCPDisconnectServerResponse,
  MCPRefreshServerRequest,
  MCPRefreshServerResponse,
  MCPGetToolsResponse,
  MCPCallToolRequest,
  MCPCallToolResponse,
  MCPGetResourcesResponse,
  MCPReadResourceRequest,
  MCPReadResourceResponse,
  MCPGetPromptsResponse,
  MCPGetPromptRequest,
  MCPGetPromptResponse,
  MCPReadConfigFileRequest,
  MCPReadConfigFileResponse,
} from './mcp.js'

// ACP types
export type {
  ACPConnectionStatus,
  ACPPermissionMode,
  ACPAgentConfig,
  ACPAgentState,
  ACPSettings,
  ACPGetAgentsResponse,
  ACPAddAgentRequest,
  ACPAddAgentResponse,
  ACPUpdateAgentRequest,
  ACPUpdateAgentResponse,
  ACPRemoveAgentRequest,
  ACPRemoveAgentResponse,
  ACPConnectAgentRequest,
  ACPConnectAgentResponse,
  ACPDisconnectAgentRequest,
  ACPDisconnectAgentResponse,
  ACPRefreshAgentRequest,
  ACPRefreshAgentResponse,
  ACPCancelSessionRequest,
  ACPCancelSessionResponse,
} from './acp.js'

// OAuth types
export type {
  OAuthStartRequest,
  OAuthStartResponse,
  OAuthCallbackRequest,
  OAuthCallbackResponse,
  OAuthStatusRequest,
  OAuthStatusResponse,
  OAuthLogoutRequest,
  OAuthLogoutResponse,
  OAuthDevicePollRequest,
  OAuthDevicePollResponse,
} from './oauth.js'

// Skills types
export type {
  SkillSource,
  SkillDefinition,
  SkillConditions,
  SkillReferenceSnapshot,
  SkillFile,
  SkillSettings,
  GetSkillsResponse,
  RefreshSkillsResponse,
  ReadSkillFileRequest,
  ReadSkillFileResponse,
  OpenSkillDirectoryRequest,
  OpenSkillDirectoryResponse,
  CreateSkillRequest,
  CreateSkillResponse,
} from './skills.js'

// Plugin types
export type {
  PluginCommandInfo,
  GetPluginCommandsResponse,
  ExecutePluginCommandRequest,
  ExecutePluginCommandResponse,
} from './plugins.js'

// Memory panel types
export type {
  MemoryDiagnosticLevel,
  MemoryDiagnosticLogEntry,
  MemoryDiagnosticStatus,
  MemoryDiagnosticSubsystem,
  MemoryLogsCleanupResponse,
  MemoryLogsListRequest,
  MemoryLogsListResponse,
  MemoryLogsStatsResponse,
  MemoryManagedFileKind,
  MemoryManagedFile,
  MemoryIndexStatus,
  MemoryDreamingStatus,
  MemoryCapturePending,
  MemoryOverview,
  MemoryGraphAuditEvent,
  MemoryGraphAuditRequest,
  MemoryGraphAuditResponse,
  MemoryGraphDeleteRequest,
  MemoryGraphDuplicate,
  MemoryGraphDuplicateDecisionRequest,
  MemoryGraphDuplicateStatus,
  MemoryGraphDuplicatesResponse,
  MemoryGraphEntitiesResponse,
  MemoryGraphEntity,
  MemoryGraphEntityResponse,
  MemoryGraphEntityType,
  MemoryGraphEntityUpsertRequest,
  MemoryGraphListRequest,
  MemoryGraphObservation,
  MemoryGraphObservationKind,
  MemoryGraphObservationResponse,
  MemoryGraphObservationUpsertRequest,
  MemoryGraphObservationsResponse,
  MemoryGraphOverview,
  MemoryGraphOverviewResponse,
  MemoryGraphRelation,
  MemoryGraphRelationResponse,
  MemoryGraphRelationUpsertRequest,
  MemoryGraphRelationsResponse,
  MemoryGraphStatus,
  MemoryReadRequest,
  MemoryReadResponse,
  MemorySearchHit,
  MemorySearchRequest,
  MemorySearchResponse,
  MemoryAppendRequest,
  MemoryAppendResponse,
  MemoryOverviewResponse,
  MemoryIndexResponse,
  MemoryCaptureDecisionRequest,
  MemoryCaptureDecisionResponse,
  MemorySaveFileRequest,
  MemorySaveFileResponse,
  MemoryRunDreamingResponse,
  CanonicalMemoryAuditEvent,
  CanonicalMemoryKind,
  CanonicalMemoryRecord,
  MemoryProfileAuditRequest,
  MemoryProfileAuditResponse,
  MemoryProfileDeleteRequest,
  MemoryProfileDeleteResponse,
  MemoryProfileExportResponse,
  MemoryProfileListRequest,
  MemoryProfileListResponse,
  MemoryProfileUpsertRequest,
  MemoryProfileUpsertResponse,
} from './memory.js'

// Scheduler types
export type {
  SchedulerRunReason,
  SchedulerTaskKind,
  SchedulerTaskSource,
  SchedulerRunStatus,
  SchedulerSchedule,
  SchedulerRunRecordDTO,
  SchedulerRunTimelineEntryDTO,
  SchedulerRunToolCallDTO,
  SchedulerRunStepDTO,
  SchedulerRunDetailDTO,
  SchedulerTaskSnapshotDTO,
  SchedulerUserTaskDTO,
  SchedulerListResponse,
  SchedulerGetRequest,
  SchedulerGetResponse,
  SchedulerRunNowRequest,
  SchedulerRunNowResponse,
  SchedulerSetEnabledRequest,
  SchedulerSetEnabledResponse,
  SchedulerCreateTaskRequest,
  SchedulerUpdateTaskRequest,
  SchedulerDeleteTaskRequest,
  SchedulerWriteTaskResponse,
  SchedulerDeleteTaskResponse,
  SchedulerListRunsRequest,
  SchedulerListRunsResponse,
  SchedulerGetRunRequest,
  SchedulerGetRunResponse,
} from './scheduler.js'

// Settings types
export type {
  ColorTheme,
  MessageListDensity,
  TypographyDensity,
  BaseTheme,
  KeyboardShortcut,
  ShortcutSettings,
  EditorSettings,
  SoulMemoryActiveSettings,
  SoulMemorySearchSettings,
  SoulMemoryEmbeddingSettings,
  SoulMemoryFlushSettings,
  SoulMemoryLogLevel,
  SoulMemoryLoggingSettings,
  SoulMemoryCaptureSettings,
  SoulMemoryReviewSettings,
  SoulMemoryCanonicalSettings,
  SoulMemoryDreamingSettings,
  SoulMemoryDailyContextSettings,
  SoulMemoryReadSettings,
  SoulMemorySettings,
  GeneralSettings,
  ChatSettings,
  NetworkSettings,
  ProxySettings,
  WechatChannelSettings,
  ChannelSettings,
  AppSettings,
  GetSettingsResponse,
  SaveSettingsRequest,
  SaveSettingsResponse,
  TestProxyRequest,
  TestProxyResponse,
} from './settings.js'

export type {
  GatewayChannelId,
  GatewayWechatLoginStatus,
  GatewayWechatStatus,
  GatewayStatus,
  GatewayGetStatusResponse,
  GatewayStartRequest,
  GatewayStartResponse,
  GatewayStopResponse,
  GatewayWechatLogoutResponse,
} from './gateway.js'

// Theme types
export type {
  ColorValue,
  ThemeDefs,
  ThemeBgColors,
  ThemeTextColors,
  ThemeBorderColors,
  ThemeShadows,
  ThemeEffects,
  ThemeNeutralColors,
  SemanticHighlightToken,
  HighlightFontStyle,
  HighlightStyle,
  HighlightLink,
  ThemeHighlightGroup,
  ThemeHighlights,
  SemanticUIToken,
  UIStyle,
  UILink,
  ThemeUIGroup,
  ThemeUITokens,
  ThemeColors,
  Theme,
  ThemeMeta,
  Base46Base30,
  Base46Base16,
  Base46Theme,
  GetThemesResponse,
  GetThemeResponse,
  ApplyThemeResponse,
  RefreshThemesResponse,
} from './themes.js'

// Permission types
export type {
  PermissionInfo,
  PermissionResponse,
  PermissionRespondRequest,
} from './permissions.js'

// Variable types
export type {
  VariablesListRequest,
  VariablesListResponse,
  VariablesSetRequest,
  VariablesSetResponse,
  VariablesDeleteRequest,
  VariablesDeleteResponse,
} from './variables.js'

// Project directories types
export type {
  ProjectDirSummary,
  ProjectDirRecord,
  ProjectDirsListResponse,
  ProjectDirsGetRequest,
  ProjectDirsGetResponse,
  ProjectDirsAddRequest,
  ProjectDirsAddResponse,
  ProjectDirsUpdateRequest,
  ProjectDirsUpdateResponse,
  ProjectDirsRemoveRequest,
  ProjectDirsRemoveResponse,
} from './project-dirs.js'

// UIMessage types
export type {
  ToolUIState,
  TextUIPart,
  ReasoningUIPart,
  FileUIPart,
  ToolUIPart,
  StepStartUIPart,
  StepsDataUIPart,
  ErrorDataUIPart,
  UIMessagePart,
  StepUIPart,
  ErrorUIPart,
  MessageMetadata,
  UIMessage,
  UIMessageChunk,
  UIMessagePartChunk,
  TokenUsage,
  SessionTokenUsage,
  UIMessageFinishChunk,
  UIMessageStreamData,
} from './ui-message.js'

export {
  isTextUIPart,
  isReasoningUIPart,
  isToolUIPart,
  isFileUIPart,
  isStepUIPart,
  isErrorUIPart,
  getToolName,
} from './ui-message.js'

// Search types
export {
  SEARCH_CATEGORIES,
  isSearchCategory,
} from './search.js'

export type {
  SearchCategory,
  SearchRequest,
  SearchResult,
  SearchResponse,
  SearchWindowGuideState,
} from './search.js'

// User prompt snippet types
export type {
  UserPrompt,
  PromptReferenceSnapshot,
  PromptListResponse,
  PromptGetRequest,
  PromptGetResponse,
  PromptCreateRequest,
  PromptCreateResponse,
  PromptUpdateRequest,
  PromptUpdateResponse,
  PromptDeleteRequest,
  PromptDeleteResponse,
} from './prompts.js'

// Todo / plan panel types
export type {
  TodoPlanScope,
  TodoPlanActivationMode,
  TodoPlanAutonomyMode,
  TodoPlanWindowActionRequest,
  TodoPlanDocument,
  TodoPlanContext,
  TodoPlanSnapshot,
  TodoPlanSettings,
  TodoPlanGetRequest,
  TodoPlanGetResponse,
  TodoPlanCreateRequest,
  TodoPlanCreateResponse,
  TodoPlanUpdateRequest,
  TodoPlanUpdateResponse,
  TodoPlanRenameRequest,
  TodoPlanRenameResponse,
  TodoPlanDeleteRequest,
  TodoPlanDeleteResponse,
  TodoPlanChangedPayload,
} from './todo-plan.js'
