/**
 * Tools Module
 * Tool-related type definitions for IPC communication
 */

import type { ThinkingEffort } from './providers.js'
import type { JsonObject, JsonSchemaObject, JsonValue } from '../json.js'

// Tool related types
export interface GetToolsResponse {
  success: boolean
  tools?: ToolDefinition[]
  error?: string
}

export interface ExecuteToolRequest {
  toolId: string
  arguments: JsonObject
  messageId: string  // Associated message ID
  sessionId: string
}

export interface ExecuteToolResponse {
  success: boolean
  result?: JsonValue
  error?: string
}

export interface ToolParameter {
  name: string
  type: 'string' | 'number' | 'boolean' | 'object' | 'array'
  description: string
  required?: boolean
  enum?: string[]
  default?: JsonValue
}

export interface ToolDefinition {
  id: string
  name: string
  description: string
  parameters: ToolParameter[]
  /** Full JSON Schema for tool parameters. Preserves nested array/object shapes for model-facing schemas. */
  parameterSchema?: JsonSchemaObject
  // Permission settings
  enabled: boolean           // Whether this tool is enabled
  autoExecute: boolean       // Whether to auto-execute when called
  permissionGuard?: 'safe' | 'sandboxed' | 'internal-check' | 'permission-gated' | 'external'
  executionMode?: ToolExecutionMode
  renderKind?: ToolRenderKind
  renderShell?: ToolRenderShell
  // Tool category for grouping in UI
  category: 'builtin' | 'custom'
  // Icon for UI display
  icon?: string
  // Tool source for UI display
  source?: 'builtin' | 'plugin' | 'mcp'  // Where the tool comes from
  serverId?: string           // MCP server ID (only for MCP tools)
  serverName?: string         // MCP server name (only for MCP tools)
}

export interface ToolResultContentPart {
  type: 'text' | 'image' | 'file'
  text?: string
  data?: string
  mimeType?: string
  path?: string
}

export interface ToolResult<TDetails = JsonObject | undefined> {
  content: ToolResultContentPart[]
  details?: TDetails
  terminate?: boolean
}

export type ToolPartialResult<TDetails = JsonObject | undefined> = ToolResult<TDetails>

export type ToolExecutionMode = 'parallel' | 'sequential'
export type ToolRenderShell = 'default' | 'self'
export type ToolRenderKind = 'text' | 'bash' | 'diff' | 'file' | 'search' | 'image' | 'custom'

export interface ToolCall {
  id: string                 // Unique ID for this tool call
  toolId: string             // ID of the tool being called
  toolName: string           // Name of the tool
  arguments: JsonObject      // Arguments passed to the tool
  status: 'pending' | 'queued' | 'executing' | 'completed' | 'failed' | 'cancelled' | 'input-streaming'
  result?: JsonValue         // Result of the tool execution
  error?: string             // Error message if failed
  rejected?: boolean         // True when the user rejected permission for this call
  rejectionReason?: string   // Optional user-provided rejection reason
  timestamp: number
  startTime?: number         // Execution start timestamp (Date.now, integer ms)
  endTime?: number           // Execution end timestamp (Date.now, integer ms)
  durationMs?: number        // Authoritative execution duration measured in the main process
  // For dangerous commands that need user confirmation
  requiresConfirmation?: boolean
  commandType?: 'read-only' | 'dangerous' | 'forbidden'
  // For edit tool: diff preview (displayed instead of arguments)
  changes?: {
    diff: string
    filePath: string
    additions: number
    deletions: number
    /** @deprecated Rollback goes through auditPath; only legacy persisted sessions still carry this. */
    originalContent?: string
    originalContentHash?: string
    afterContentHash?: string
    auditId?: string
    auditPath?: string
  }
  // For streaming tool input
  // Shows partial args JSON as it's being generated by the model
  streamingArgs?: string
  // Pending permission request fields (set when permission:request fires)
  permissionId?: string       // ID of the pending permission request
  canRespond?: boolean        // Whether this UI can respond (vs read-only mirror)
  // Waiting behind another prompt in the session's serialized permission
  // queue (permission:queued fired, no card yet)
  permissionQueued?: boolean
}

// Bash tool specific settings
export interface BashToolSettings {
  enableSandbox: boolean              // Whether to enable directory sandbox
  defaultWorkingDirectory?: string    // Default working directory for commands
  allowedDirectories: string[]        // List of allowed directories
  confirmDangerousCommands: boolean   // Whether to confirm dangerous commands
  dangerousCommandWhitelist: string[] // Commands to skip confirmation (e.g., "npm install")
}

// Web Search settings
export interface WebSearchSettings {
  enabled: boolean                // Master switch for web search
  braveApiKey?: string            // Brave Search API key
  defaultProvider?: 'brave'       // Default search provider (extensible)
  defaultCount?: number           // Default number of results (1-10)
}

export type PermissionMode = 'normal' | 'auto-accept-edits' | 'dangerously-allow-all'

export interface ToolCallModelSettings {
  /** Provider used for lightweight AI utility calls, memory background tasks, and dreaming. Empty = use chat default. */
  providerId?: string
  /** Model used for lightweight AI utility calls, memory background tasks, and dreaming. Empty = provider default model. */
  model?: string
  /** Independent thinking toggle for lightweight AI utility calls. Defaults to disabled. */
  thinking?: boolean
  /** Thinking effort used only when lightweight utility thinking is enabled. */
  thinkingEffort?: ThinkingEffort
}

export interface ToolSettings {
  // Global tool settings
  enableToolCalls: boolean   // Master switch for tool calls
  permissionMode?: PermissionMode // Session/runtime permission mode (global default for now)
  toolCallModel?: ToolCallModelSettings
  // Per-tool settings (toolId -> settings)
  tools: Record<string, {
    enabled: boolean
    autoExecute: boolean
  }>
  // Bash tool specific settings
  bash?: BashToolSettings
  // Web Search settings
  webSearch?: WebSearchSettings
}

// Stream message types
export interface StreamMessageChunk {
  type: 'text' | 'reasoning' | 'error' | 'complete' | 'tool_call' | 'tool_result'
  content: string
  messageId?: string
  reasoning?: string
  toolCall?: ToolCall
}

export interface SendMessageStreamResponse {
  success: boolean
  chunk?: StreamMessageChunk
  error?: string
  errorDetails?: string
}
