import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

function readRendererFile(relativePath: string) {
  return readFileSync(new URL(`../../${relativePath}`, import.meta.url), 'utf8')
}

describe('App container layout', () => {
  it('uses Splitter for the app shell and both sidebars', () => {
    const app = readRendererFile('App.vue')

    expect(app).toContain("import Container from '@/components/common/Container.vue'")
    expect(app).toContain("import Splitter from '@/components/common/Splitter.vue'")
    expect(app).toContain("import SplitterPanel from '@/components/common/SplitterPanel.vue'")
    expect(app).toContain("import RightWorkbenchPanel from '@/components/workbench/RightWorkbenchPanel.vue'")
    expect(app).not.toContain("import ChatInspectorPanel from '@/components/chat/ChatInspectorPanel.vue'")
    expect(app).not.toContain("import SidebarResizeHandle from '@/components/sidebar/SidebarResizeHandle.vue'")
    expect(app).toContain('class="app-shell"')
    expect(app).toContain(':class="{ \'is-sidebar-resizing\': sidebarResizing }"')
    expect(app).toContain('v-if="sidebarDockedVisible"')
    expect(app).toContain('v-model:size="sidebarWidth"')
    expect(app).toContain('class="app-left-sidebar-region"')
    expect(app).toContain('size-unit="px"')
    expect(app).toContain(':min="MIN_SIDEBAR_WIDTH"')
    expect(app).toContain(':max="MAX_SIDEBAR_WIDTH"')
    expect(app).toContain('flex\n        class="app-shell-main-region"')
    expect(app).toContain('class="app-shell-main-region"')
    expect(app).toContain(':resizable="sidebarDockedVisible"')
    expect(app).toContain('@resize-start="handleSidebarResizeStart"')
    expect(app).toContain('@resize-end="handleSidebarResizeEnd"')
    expect(app).toContain('const sidebarResizing = ref(false)')
    expect(app).toContain('const sidebarDockedVisible = computed')
    expect(app).not.toContain('sidebarPanelSizeFromWidth')
    expect(app).not.toContain('sidebarWidthFromPanelSize')
    expect(app).not.toContain('const sidebarPanelSize = ref')
    expect(app).not.toContain('const appMainPanelSize = computed')
    expect(app).not.toContain('watch(sidebarPanelSize')
    expect(app).not.toContain("const appLeftSidebarFlex = '0 0 auto'")
    expect(app).not.toContain('const appLeftSidebarRegionStyle = computed')
    expect(app).not.toContain(':sidebar-style="appLeftSidebarRegionStyle"')
    expect(app).toContain('--app-sidebar-transition-duration: 0.3s')
    expect(app).toContain('--app-sidebar-transition-ease: cubic-bezier(0.4, 0, 0.2, 1)')
    expect(app).toContain('animating it relayouts the full message list every frame')
    expect(app).toContain('.app-sidebar-actions.transitioning {\n  transition: none;')
    expect(app).not.toContain('transition: inline-size var(--app-sidebar-transition-duration) var(--app-sidebar-transition-ease)')
    expect(app).not.toContain('transition: left var(--app-sidebar-transition-duration) var(--app-sidebar-transition-ease)')
    expect(app).not.toContain('flex-basis 0.3s')
    expect(app).toContain('.app-shell.is-sidebar-resizing :deep(.app-left-sidebar-region)')
    expect(app).toContain('class="app-content"')
    expect(app).toContain('class="app-content-splitter"')
    expect(app).toContain('@resize-start="inspectorResizing = true"')
    expect(app).toContain('@resize-end="handleInspectorResizeEnd"')
    expect(app).toContain('v-model:size="mainWorkspacePanelSize"')
    expect(app).toContain(':resizable="inspectorVisible"')
    expect(app).toContain('v-model:size="inspectorPanelSize"')
    expect(app).toContain('class="app-right-sidebar-region"')
    expect(app).toContain('<RightWorkbenchPanel')
    expect(app).toContain('ref="rightWorkbenchRef"')
    expect(app).toContain(':workspace-root="currentWorkspaceRoot"')
    expect(app).toContain(':workspace-roots="currentWorkspaceRoots"')
    expect(app).toContain('@open-file="openFileInRightWorkbench"')
    expect(app).toContain('const rightWorkbenchRef = ref<InstanceType<typeof RightWorkbenchPanel> | null>(null)')
    expect(app).toContain('async function openFileInRightWorkbench(filePath: string)')
    expect(app).toContain('await rightWorkbenchRef.value?.openFile(filePath)')
    expect(app).not.toContain('class="inspector-resize-handle"')
    expect(app).not.toContain('edge="left"')
    expect(app).not.toContain('@resize="handleInspectorPixelResize"')
    expect(app).toContain('const inspectorPanelSize = ref(clampInspectorPanelSize(')
    expect(app).toContain('localStorage.getItem(\'inspectorPanelSize\')')
    expect(app).not.toContain('function handleInspectorPixelResize(width: number)')
    expect(app).toContain('function handleInspectorResizeEnd()')
    expect(app).toContain('localStorage.setItem(\'inspectorPanelSize\', String(inspectorPanelSize.value))')
    expect(app).not.toContain('const INSPECTOR_SIDEBAR_WIDTH')
    expect(app).not.toContain('const appRightSidebarRegionStyle = computed')
    expect(app).not.toContain(':sidebar-style="appRightSidebarRegionStyle"')
    expect(app).not.toContain('sidebar-position="right"')
    expect(app).toContain('class="app-main-region"')
    expect(app).toContain('body-class="app-main-body"')
    expect(app).toContain('main-class="app-main-content-region"')
    expect(app).toContain('class="workspace-view-stack"')
    expect(app).toContain(':data-active-workspace-view="activeWorkspaceView"')
    expect(app).toContain('v-show="activeWorkspaceView === \'chat\'"')
    expect(app).toContain('class="workspace-view workspace-view-chat"')
    expect(app).toContain('v-show="workspacePanelOpen"')
    expect(app).toContain('class="workspace-view workspace-view-panel"')
    expect(app).toContain(':active-tab="activeWorkspacePanel"')
    expect(app).toContain("const activeWorkspaceView = computed(() => activeWorkspacePanel.value ?? 'chat')")
    expect(app).not.toContain('v-if="activeWorkspacePanel"')
    expect(app).not.toContain('v-show="!activeWorkspacePanel"')
  })

  it('uses Container for the chat main header and content regions', () => {
    const chatWindow = readRendererFile('components/chat/ChatWindow.vue')

    expect(chatWindow).toContain("import Container from '@/components/common/Container.vue'")
    expect(chatWindow).toContain("import ChatSidePanel from './ChatSidePanel.vue'")
    expect(chatWindow).toContain('class="chat"')
    expect(chatWindow).toContain('body-class="chat-body"')
    expect(chatWindow).toContain('main-class="chat-main-region"')
    expect(chatWindow).not.toContain('footer-class="chat-footer-region"')
    expect(chatWindow).toContain('sidebar-position="right"')
    expect(chatWindow).toContain(':sidebar-class="[\'chat-side-region\', { collapsed: sidePanelCollapsed }]"')
    expect(chatWindow).toContain('<template #header>')
    expect(chatWindow).toContain('#sidebar')
    expect(chatWindow).not.toContain('<template #footer>')
    expect(chatWindow).toContain('class="tab-content"')
    expect(chatWindow).toContain('ref="chatFooterRef"')
    expect(chatWindow).toContain(':footer-target="chatFooterRef"')
    expect(chatWindow).toContain(':sidebar-width="chatSidePanelWidth"')
    expect(chatWindow).toContain(':side-panel-available="sidePanelAvailable"')
    expect(chatWindow).toContain(':side-panel-collapsed="sidePanelCollapsed"')
    expect(chatWindow).toContain(':outline-rail-target="!sidePanelCollapsed ? chatSideOutlineTarget : null"')
    expect(chatWindow).toContain('v-if="sidePanelVisible"')
    expect(chatWindow).toContain('const sidePanelVisible = computed(() => sidePanelAvailable.value || !sidePanelCollapsed.value)')
    expect(chatWindow).toContain('@outline-target-change="handleSideOutlineTargetChange"')
    expect(chatWindow).toContain('@toggle-collapsed="toggleSidePanelCollapsed"')
    expect(chatWindow).toContain('@toggle-side-panel="toggleSidePanelCollapsed"')
    expect(chatWindow).toContain('const CHAT_SIDE_PANEL_COLLAPSED_WIDTH = 0')
    expect(chatWindow).not.toContain('outlineTargetChange')
    expect(chatWindow).toContain('chatSideOutlineTarget')
    expect(chatWindow).not.toContain('border-left')
  })

  it('keeps docked sidebar content fixed while the outer container animates', () => {
    const sidebar = readRendererFile('components/sidebar/Sidebar.vue')

    expect(sidebar).toContain("'--sidebar-docked-width': `${props.width}px`")
    expect(sidebar).toContain('width: var(--sidebar-docked-width)')
    expect(sidebar).toContain('min-width: var(--sidebar-docked-width)')
    expect(sidebar).toContain('max-width: var(--sidebar-docked-width)')
    expect(sidebar).toContain('.sidebar.floating .sidebar-content')
    expect(sidebar).toContain(':aria-hidden="collapsed && !floating"')
    expect(sidebar).not.toContain('v-show="showContent"')
    expect(sidebar).not.toContain('const showContent = computed')
    expect(sidebar).not.toContain('width: collapsed.value')
    expect(sidebar).not.toContain('maxWidth: collapsed.value')
    expect(sidebar).not.toContain('width 0.3s cubic-bezier')
    expect(sidebar).not.toContain('max-width 0.3s cubic-bezier')
    expect(sidebar).not.toContain('<SidebarResizeHandle')
    expect(sidebar).not.toContain("import SidebarResizeHandle from './SidebarResizeHandle.vue'")
  })

  it('keeps floating sidebar width and close behavior tied to the sidebar component', () => {
    const app = readRendererFile('App.vue')
    const sidebar = readRendererFile('components/sidebar/Sidebar.vue')

    expect(app).toContain('@request-floating-close="closeFloatingSidebar"')
    expect(app).toContain('@request-floating-keep-open="keepFloatingSidebarOpen"')
    expect(app).toContain('let floatingCloseTimer: ReturnType<typeof setTimeout> | null = null')
    expect(app).toContain('let floatingCooldownTimer: ReturnType<typeof setTimeout> | null = null')
    expect(app).toContain('function keepFloatingSidebarOpen()')
    expect(app).not.toContain('@mouseleave="handleSidebarMouseLeave"')
    expect(app).not.toContain('function handleSidebarMouseLeave')
    expect(app).not.toContain('sidebarFloating.value ? 280 : 0')

    expect(sidebar).toContain('@mouseenter="handleMouseEnter"')
    expect(sidebar).toContain('@mouseleave="handleMouseLeave"')
    expect(sidebar).toContain("'request-floating-keep-open': []")
    expect(sidebar).toContain("'request-floating-close': []")
    expect(sidebar).toContain("emit('request-floating-keep-open')")
    expect(sidebar).toContain("emit('request-floating-close')")
    expect(sidebar).toContain('--sidebar-floating-safe-zone: 36px')
    expect(sidebar).toContain('+ var(--sidebar-floating-safe-zone)')
    expect(sidebar).toContain('width: var(--sidebar-docked-width);')
    expect(sidebar).toContain('pointer-events: auto;')
    expect(sidebar).not.toContain('width: 300px !important')
    expect(sidebar).not.toContain('max-width: 300px !important')
  })

  it('keeps tab reservation width changes discrete during sidebar toggle', () => {
    const tabBar = readRendererFile('components/chat/TabBar.vue')

    expect(tabBar).toContain('Width changes stay discrete to avoid')
    expect(tabBar).toContain('transition: none;')
    expect(tabBar).not.toContain('width var(--app-sidebar-transition-duration, 0.3s)')
    expect(tabBar).not.toContain('padding-left var(--app-sidebar-transition-duration, 0.3s)')
    expect(tabBar).not.toContain('var(--app-sidebar-transition-ease, cubic-bezier(0.4, 0, 0.2, 1))')
    expect(tabBar).not.toContain('width 0.3s cubic-bezier')
    expect(tabBar).not.toContain('padding-left 0.3s cubic-bezier')
  })

  it('uses the right workbench with dynamic tabs and the shared file layout components', () => {
    const app = readRendererFile('App.vue')
    const workbench = readRendererFile('components/workbench/RightWorkbenchPanel.vue')
    const editor = readRendererFile('components/editor/EditorWorkbench.vue')

    expect(app).toContain('const MIN_INSPECTOR_PANEL_SIZE = 22')
    expect(app).toContain('const MAX_INSPECTOR_PANEL_SIZE = 48')
    expect(app).toContain('const DEFAULT_INSPECTOR_PANEL_SIZE = 32')
    expect(app).toContain('const currentWorkspaceRoots = computed')
    expect(app).toContain('const currentWorkspaceRoot = computed')
    expect(app).toContain('return Math.min(MAX_INSPECTOR_PANEL_SIZE, Math.max(MIN_INSPECTOR_PANEL_SIZE, size))')
    expect(app).toContain(':min="22"')
    expect(app).toContain(':max="48"')
    expect(app).not.toContain(':min-width="inspectorMinWidth"')
    expect(app).not.toContain(':max-width="inspectorMaxWidth"')
    expect(app).not.toContain('const MIN_INSPECTOR_PANEL_WIDTH = 320')
    expect(app).not.toContain('const MAX_INSPECTOR_PANEL_WIDTH = 720')

    expect(workbench).toContain("import Container from '@/components/common/Container.vue'")
    expect(workbench).toContain("import Tabs from '@/components/common/Tabs.vue'")
    expect(workbench).toContain("import TabPane from '@/components/common/TabPane.vue'")
    expect(workbench).toContain("import EditorWorkbench from '@/components/editor/EditorWorkbench.vue'")
    expect(workbench).toContain("import { useEditorWorkspace } from '@/composables/useEditorWorkspace'")
    expect(workbench).toContain("type WorkbenchTabType = 'files' | 'file' | 'terminal' | 'browser'")
    expect(workbench).toContain('addable')
    expect(workbench).toContain('closable')
    expect(workbench).toContain('@tab-add="togglePicker"')
    expect(workbench).toContain(':initial-file-path="tab.filePath"')
    expect(workbench).toContain('@open-file="openFile"')
    expect(workbench).toContain('async function openFile(filePath: string)')
    expect(workbench).toContain("type: 'file'")
    expect(workbench).toContain('title: basename(filePath)')
    expect(workbench).toContain('await editorWorkspace.openFile(filePath)')
    expect(workbench).toContain('defineExpose({\n  openFile,\n})')
    expect(workbench).toContain("window.electronAPI.executeTool(\n      'bash'")
    expect(workbench).toContain('<iframe')
    expect(workbench).not.toContain('Session Lens')
    expect(workbench).not.toContain('lastModel')

    expect(editor).toContain("import Container from '@/components/common/Container.vue'")
    expect(editor).toContain("import Breadcrumb from '@/components/common/Breadcrumb.vue'")
    expect(editor).toContain("import Splitter from '@/components/common/Splitter.vue'")
    expect(editor).toContain("import SplitterPanel from '@/components/common/SplitterPanel.vue'")
    expect(editor).toContain('<Breadcrumb')
    expect(editor).toContain('overflow: hidden;')
    expect(editor).toContain('overflow-x: auto;')
    expect(editor).toContain('font-size: 12px;')
    expect(editor).toContain(':deep(.app-breadcrumb__list)')
    expect(editor).toContain('flex-wrap: nowrap;')
    expect(editor).toContain('white-space: nowrap;')
    expect(editor).toContain(':deep(.app-breadcrumb-item.is-last)')
    expect(editor).toContain('const parts: Array<{ label: string; path: string }> = []')
    expect(editor).not.toContain('{ label: basename(normalizedRoot), path: normalizedRoot }')
    expect(editor).toContain('const editorPanelSize = ref(62)')
    expect(editor).toContain('const explorerPanelSize = ref(38)')
    expect(editor).toContain(':min="28"')
    expect(editor).toContain(':max="58"')
    expect(editor).not.toContain('<EditorTabStrip')
    expect(editor).not.toContain("import EditorTabStrip from './EditorTabStrip.vue'")
    expect(editor).toContain('const explorerCollapsed = ref(false)')
    expect(editor).toContain("@click=\"explorerCollapsed = !explorerCollapsed\"")
    expect(editor).toContain('v-if="!explorerCollapsed"')
    expect(editor).toContain(':resizable="!explorerCollapsed"')
    expect(editor).toContain('class="editor-panel"')
    expect(editor).toContain('class="explorer-panel"')
    expect(editor).toContain('<FileExplorer')
    expect(editor).toContain(':workspace-root="workspaceRoot"')
    expect(editor).not.toContain('initialFilePath: string')
    expect(editor).not.toContain("return [{ label: 'Workspace', path: 'workspace' }]")
    expect(editor).not.toContain('basename(root || activePath)')
  })

  it('defers expensive message-list measurements during sidebar layout transitions', () => {
    const app = readRendererFile('App.vue')
    const chatContainer = readRendererFile('components/ChatContainer.vue')
    const chatWindow = readRendererFile('components/chat/ChatWindow.vue')
    const chatPanel = readRendererFile('components/chat/ChatPanel.vue')
    const messageList = readRendererFile('components/chat/MessageList.vue')

    expect(app).toContain(':layout-transitioning="sidebarActionAnimating"')
    expect(chatContainer).toContain(':layout-transitioning="layoutTransitioning"')
    expect(chatContainer).toContain('<div class="chat-container-wrapper">')
    expect(chatContainer).not.toContain('sidebar-collapsed')
    expect(chatContainer).not.toContain('transition: padding-left')
    expect(chatWindow).toContain(':layout-transitioning="layoutTransitioning"')
    expect(chatPanel).toContain(':layout-transitioning="props.layoutTransitioning"')
    expect(chatPanel).toContain(':outline-rail-target="props.outlineRailTarget"')
    expect(chatPanel).toContain('layoutTransitioning?: boolean')
    expect(chatPanel).toContain('outlineRailTarget?: HTMLElement | null')
    expect(chatPanel).toContain("function deferChatPanelMeasurementDuringTransition(kind: 'composer' | 'content-column'): boolean")
    expect(chatPanel).toContain("if (deferChatPanelMeasurementDuringTransition('composer')) return")
    expect(chatPanel).toContain("if (deferChatPanelMeasurementDuringTransition('content-column')) return")
    expect(chatPanel).toContain('return [composerContainerRef.value].filter')
    expect(chatPanel).toContain('pendingComposerResizeHeight = getResizeEntryBlockSize(entry)')
    expect(chatPanel).toContain("composerResizeObserver.observe(composer, { box: 'border-box' })")
    expect(chatPanel).toContain('deferredLayoutMeasureTimer = setTimeout')
    expect(messageList).toContain('layoutTransitioning?: boolean')
    expect(messageList).toContain('outlineRailTarget?: HTMLElement | null')
    expect(messageList).toContain('function deferLayoutMeasurementDuringTransition(): boolean')
    expect(messageList).toContain('function cancelPendingLayoutMeasurementFrames()')
    expect(messageList).toContain('cancelPendingLayoutMeasurementFrames()')
    expect(messageList).toContain('if (deferLayoutMeasurementDuringTransition()) return')
    expect(messageList).toContain('deferredLayoutMeasurementRefresh = false')
    expect(messageList).toContain('deferredLayoutMeasurementTimer = setTimeout')
    expect(messageList).toContain('}, 700)')
    expect(messageList).toContain('deferredLayoutMeasurementFollowupTimer = setTimeout')
    expect(messageList).toContain('left: 50%;')
    expect(messageList).not.toContain('left: var(--chat-content-column-center, 50%);')
  })

  it('routes outline into the side panel while trail remains in the message panel', () => {
    const messageList = readRendererFile('components/chat/MessageList.vue')
    const userRail = readRendererFile('components/chat/UserMessageNavRail.vue')
    const assistantRail = readRendererFile('components/chat/AssistantMessageNavRail.vue')
    const sidePanel = readRendererFile('components/chat/ChatSidePanel.vue')
    const tabBar = readRendererFile('components/chat/TabBar.vue')
    const todoProgress = readRendererFile('components/chat/TodoProgressPanel.vue')

    expect(messageList).toContain('<Teleport')
    expect(messageList).toContain(':to="props.outlineRailTarget || \'body\'"')
    expect(messageList).toContain(':disabled="!useSideOutlineRail"')
    expect(messageList).toContain('v-if="useSideOutlineRail && hasAssistantOutlineNav"')
    expect(messageList).toContain('placement="side"')
    expect(messageList).toContain('<UserMessageNavRail')
    expect(messageList).toContain('<AssistantMessageNavRail')
    expect(messageList).toContain('v-if="hasUserNavTrail"')
    expect(messageList).toContain(':panel-available="hasNavPanelRoom"')
    expect(messageList).toContain('placement="overlay"')
    expect(messageList).toContain('const useSideOutlineRail = computed(() => Boolean(props.outlineRailTarget))')

    expect(userRail).toContain("placement?: 'overlay' | 'side'")
    expect(userRail).toContain("placement: 'overlay'")
    expect(userRail).toContain('.user-nav-rail.placement-side')
    expect(userRail).toContain('v-if="!isSidePlacement && panelAvailable && effectiveOpen"')
    expect(userRail).toContain('const effectiveOpen = computed(() => isSidePlacement.value || isOpen.value)')
    expect(userRail).not.toContain('props.panelAvailable && !isAutoPanelDismissed.value')
    expect(assistantRail).toContain("placement?: 'overlay' | 'side'")
    expect(assistantRail).toContain("placement: 'overlay'")
    expect(assistantRail).toContain('.assistant-nav-rail.placement-side')
    expect(assistantRail).toContain("import Scrollbar from '@/components/common/Scrollbar.vue'")
    expect(assistantRail).toContain('v-if="isSidePlacement"')
    expect(assistantRail).toContain('class="assistant-nav-side-scroll"')
    expect(assistantRail).toContain('class="assistant-nav-side-list"')
    expect(assistantRail).toContain(':data-assistant-nav-index="marker.navIndex"')
    expect(assistantRail).toContain('function scrollActiveSideMarkerIntoView()')
    expect(assistantRail).toContain("behavior: 'smooth'")
    expect(assistantRail).toContain('v-if="!isSidePlacement && showScrollThumb"')
    expect(assistantRail).toContain('v-if="!isSidePlacement && hasPreviousPage"')
    expect(assistantRail).toContain('v-if="!isSidePlacement && panelAvailable && effectiveOpen"')

    expect(sidePanel).toContain('ref="outlineHostRef"')
    expect(sidePanel).toContain('class="chat-side-section chat-side-outline-section"')
    expect(sidePanel).toContain("emit('outlineTargetChange', props.collapsed ? null : outlineHostRef.value)")
    expect(sidePanel).not.toContain('chat-side-panel-toggle')
    expect(sidePanel).toContain('background: transparent;')
    expect(sidePanel).toContain('.chat-side-panel.collapsed')
    expect(sidePanel).toContain('padding: 0;')
    expect(tabBar).toContain('sidePanelAvailable?: boolean')
    expect(tabBar).toContain('sidePanelCollapsed?: boolean')
    expect(tabBar).toContain('class="header-btn side-panel-toggle"')
    expect(tabBar).not.toContain('v-if="sidePanelAvailable"')
    expect(tabBar).toContain("toggleSidePanel: []")
    expect(sidePanel).toContain('<TodoProgressPanel')
    expect(sidePanel).toContain("window.addEventListener('todo-plan:toggle-card', handleTodoToggleCard)")
    expect(todoProgress).toContain('window.electronAPI.getTodoPlan')
    expect(todoProgress).toContain('window.electronAPI.onTodoPlanChanged')
    expect(todoProgress).toContain('parseTasks')
  })

  it('lets workspace loading states fill memory and media panels', () => {
    const mediaPanel = readRendererFile('components/MediaPanel.vue')
    const memoryPanel = readRendererFile('components/memory/MemoryPanelContent.vue')

    expect(memoryPanel).toContain('type="grid"')
    expect(memoryPanel).toContain('.memory-page-shell :deep(.page-shell-body) {\n  display: flex;\n  flex-direction: column;\n  min-height: 0;\n  overflow: hidden;')
    expect(memoryPanel).toContain('.memory-single-page {\n  --memory-table-height: clamp(96px, 30vh, 360px);')
    expect(memoryPanel).toContain('flex: 1 1 auto;\n  width: 100%;\n  height: 100%;')
    expect(memoryPanel).toContain('.profile-section {\n  display: flex;\n  flex-direction: column;\n  min-height: 0;')
    expect(memoryPanel).toContain('.profile-section :deep(.collapse-panel-content-shell) {\n  flex: 1 1 auto;')
    expect(memoryPanel).toContain('.profile-section :deep(.collapse-panel-content.simple-profile-list) {\n  height: 100%;')
    expect(memoryPanel).toContain('@media (max-height: 520px) {\n  .memory-single-page {\n    grid-template-rows: minmax(0, 1fr) minmax(0, 1fr);')
    expect(memoryPanel).toContain('.loading-state {\n  flex: 1 1 auto;')
    expect(memoryPanel).toContain('height: 100%;\n  padding: 0 20px;')

    expect(mediaPanel).toContain('.media-panel {\n  width: 560px;\n  height: 100%;\n  min-height: 0;\n  min-width: 0;')
    expect(mediaPanel).toContain('.media-panel.mode-main {\n  flex: 1 1 auto;\n  width: auto;\n  height: 100%;')
    expect(mediaPanel).toContain('.media-content {\n  flex: 1 1 auto;\n  display: flex;\n  flex-direction: column;\n  min-height: 0;\n  min-width: 0;')
    expect(mediaPanel).toContain('.content-body {\n  position: relative;\n  z-index: 0;\n  flex: 1 1 auto;\n  display: flex;\n  flex-direction: column;\n  min-height: 0;')
    expect(mediaPanel).toContain('.loading-state,\n.empty-state {\n  flex: 1 1 auto;\n  box-sizing: border-box;\n  width: 100%;')
    expect(mediaPanel).toContain('padding: 20px;')
  })

  it('keeps workspace panels as cached sibling views instead of overlay transitions', () => {
    const app = readRendererFile('App.vue')
    const mediaPanel = readRendererFile('components/MediaPanel.vue')

    expect(app).toContain('class="workspace-view-stack"')
    expect(app).toContain('v-show="activeWorkspaceView === \'chat\'"')
    expect(app).toContain('v-show="workspacePanelOpen"')
    expect(mediaPanel).toContain('v-show="visible"')
    expect(mediaPanel).toContain("type WorkspacePanelNav = 'media' | 'memory' | 'agents' | 'tasks' | 'archive'")
    expect(mediaPanel).toContain('const mountedNavs = ref<WorkspacePanelNav[]>([activeNav.value])')
    expect(mediaPanel).toContain('function hasMountedNav(nav: WorkspacePanelNav): boolean')
    expect(mediaPanel).toContain('v-if="hasMountedNav(\'memory\')"')
    expect(mediaPanel).toContain('data-workspace-panel-view="memory"')
    expect(mediaPanel).toContain('.workspace-panel-views {')
    expect(mediaPanel).toContain('.workspace-panel-view {')
    expect(mediaPanel).not.toContain('<Transition name="media-panel">')
    expect(mediaPanel).not.toContain('media-panel-enter-active')
    expect(mediaPanel).not.toContain('v-else-if="activeNav === \'memory\'"')
  })

  it('drives sidebar panels and sessions through one Menu active index', () => {
    const app = readRendererFile('App.vue')
    const sidebar = readRendererFile('components/sidebar/Sidebar.vue')
    const sessionList = readRendererFile('components/sidebar/SessionList.vue')

    expect(sidebar).toContain("import MenuItem from '@/components/common/MenuItem.vue'")
    expect(sidebar).toContain(':active-index="activeSidebarIndex"')
    expect(sidebar).toContain('@menu-select="handleSidebarMenuSelect"')
    expect(sidebar).toContain("return `panel:${panel}`")
    expect(sidebar).toContain("return `session:${sessionId}`")
    expect(sidebar).toContain("'select-session': [sessionId: string]")
    expect(sidebar).not.toContain('@session-click')
    expect(sidebar).not.toContain(':class="{ active: activeWorkspacePanel === action.id }"')

    expect(sessionList).toContain("import AppMenu from '@/components/common/Menu.vue'")
    expect(sessionList).toContain("import SubMenu from '@/components/common/SubMenu.vue'")
    expect(sessionList).toContain('<AppMenu')
    expect(sessionList).toContain(':model-value="activeIndex"')
    expect(sessionList).toContain("emit('menu-select', index)")
    expect(sessionList).toContain('item-as="div"')
    expect(sessionList).toContain('raw')
    expect(sessionList).not.toContain('CollapseGroup')
    expect(sessionList).not.toContain('CollapsePanel')

    expect(app).toContain('@select-session="selectSidebarSession"')
    expect(app).toContain('activeWorkspacePanel.value = panel')
    expect(app).toContain('async function selectSidebarSession(sessionId: string)')
    expect(app).toContain('activeWorkspacePanel.value = null\n  await sessionsStore.switchSession(sessionId)')
    expect(app).not.toContain('activeWorkspacePanel.value === panel ? null : panel')
  })
})
