import type { Step, ToolCall, ToolPartialResult } from '@/types'

export type ToolAuditState = 'permission' | 'completed' | 'failed' | 'expanded'

export interface ToolAuditCase {
  id: string
  toolName: string
  state: ToolAuditState | 'streaming' | 'group' | 'flow'
  title: string
  note: string
  steps: Step[]
  autoExpand?: boolean
}

interface ToolSpec {
  toolName: string
  label: string
  args: Record<string, unknown>
  doneOutput: string
  failError: string
  partial?: ToolPartialResult
  changes?: ToolCall['changes']
}

const BASE_TIME = Date.now() - 20_000
const ROOT = '/Users/yitiansong/data/code/start-electron'

const editDiff = [
  '--- a/src/renderer/components/chat/StepsPanel.vue',
  '+++ b/src/renderer/components/chat/StepsPanel.vue',
  '@@ -1,5 +1,7 @@',
  ' const state = ref(false)',
  '-const label = "Tool"',
  '+const label = "Tool activity"',
  '+const compact = true',
  ' export default state',
].join('\n')

const writeDiff = [
  '--- /dev/null',
  '+++ b/docs/tool-ui-audit/example.md',
  '@@ -0,0 +1,5 @@',
  '+# Tool UI audit',
  '+',
  '+This file is generated by the write tool.',
  '+It should preview content while streaming.',
  '+Done.',
].join('\n')

function textResult(text: string, details?: Record<string, unknown>): ToolPartialResult {
  return {
    content: [{ type: 'text', text }],
    details,
  }
}

const specs: ToolSpec[] = [
  {
    toolName: 'bash',
    label: 'bash',
    args: { command: 'bun run test -- src/renderer/stores/__tests__/tool-display.test.ts' },
    doneOutput: [
      '> bun run test -- src/renderer/stores/__tests__/tool-display.test.ts',
      '✓ src/renderer/stores/__tests__/tool-display.test.ts (12 tests)',
      'Done in 1.8s',
    ].join('\n'),
    failError: 'Command failed: bun run build:check\nsrc/renderer/components/chat/StepsPanel.vue:144: Type error in activity row.',
  },
  {
    toolName: 'read',
    label: 'read',
    args: { path: `${ROOT}/src/renderer/components/chat/StepsPanel.vue`, offset: 120, limit: 18 },
    doneOutput: Array.from({ length: 14 }, (_, index) => `${120 + index}: const auditLine${index + 1} = true`).join('\n'),
    failError: `Failed to read ${ROOT}/missing.ts: ENOENT: no such file or directory.`,
  },
  {
    toolName: 'edit',
    label: 'edit',
    args: {
      path: `${ROOT}/src/renderer/components/chat/StepsPanel.vue`,
      edits: [{ oldText: 'const label = "Tool"', newText: 'const label = "Tool activity"' }],
    },
    doneOutput: 'Successfully edited src/renderer/components/chat/StepsPanel.vue. 1 replacement.',
    failError: 'Failed to edit src/renderer/components/chat/StepsPanel.vue: text not found in file.\nThe requested oldText does not match current contents.',
    changes: {
      diff: editDiff,
      filePath: `${ROOT}/src/renderer/components/chat/StepsPanel.vue`,
      additions: 2,
      deletions: 1,
    },
  },
  {
    toolName: 'write',
    label: 'write',
    args: {
      path: `${ROOT}/docs/tool-ui-audit/example.md`,
      content: '# Tool UI audit\n\nThis file is generated by the write tool.\nIt should preview content while streaming.\nDone.\n',
    },
    doneOutput: 'Wrote docs/tool-ui-audit/example.md (+5 -0).',
    failError: 'Failed to write docs/tool-ui-audit/example.md: file changed after permission approval and diff changed.',
    changes: {
      diff: writeDiff,
      filePath: `${ROOT}/docs/tool-ui-audit/example.md`,
      additions: 5,
      deletions: 0,
    },
  },
  {
    toolName: 'grep',
    label: 'grep',
    args: { pattern: 'requiresConfirmation', path: `${ROOT}/src`, glob: '**/*.{ts,vue}' },
    doneOutput: 'src/renderer/stores/helpers/tool-status.ts:32 requiresConfirmation\nsrc/renderer/stores/chat.ts:607 requiresConfirmation = true',
    failError: 'grep failed: ripgrep exited with status 2\nregex parse error: unclosed character class.',
  },
  {
    toolName: 'glob',
    label: 'glob',
    args: { pattern: 'src/renderer/components/chat/*.vue', path: ROOT },
    doneOutput: 'src/renderer/components/chat/StepsPanel.vue\nsrc/renderer/components/chat/ToolStepDetails.vue\nsrc/renderer/components/chat/ToolResultRenderer.vue',
    failError: 'glob failed: invalid glob pattern: src/[renderer',
  },
  {
    toolName: 'find',
    label: 'find',
    args: { pattern: 'Tool*.vue', path: `${ROOT}/src/renderer/components/chat` },
    doneOutput: 'ToolActivityDetails.vue\nToolDiffPreview.vue\nToolResultRenderer.vue\nToolStepDetails.vue',
    failError: 'find failed: search path does not exist: src/renderer/components/missing',
  },
  {
    toolName: 'ls',
    label: 'ls',
    args: { path: `${ROOT}/src/renderer/components/chat` },
    doneOutput: 'StepsPanel.vue\nToolActivityDetails.vue\nToolDiffPreview.vue\nToolResultRenderer.vue\nToolStepDetails.vue',
    failError: 'ls failed: permission denied: /private/var/root',
  },
  {
    toolName: 'variable',
    label: 'variable',
    args: { action: 'set', name: 'workdir', value: ROOT },
    doneOutput: 'Set workdir = /Users/yitiansong/data/code/start-electron',
    failError: 'variable failed: cannot update readonly variable: system',
    partial: textResult('', {
      variables: [
        { name: 'workdir', value: ROOT, scope: 'session', description: 'Current workspace root' },
        { name: 'theme', value: 'obsidian', scope: 'global', description: 'Active theme' },
      ],
    }),
  },
  {
    toolName: 'todo_plan',
    label: 'todo_plan',
    args: { action: 'update', title: 'Tool UI audit', scope: 'session' },
    doneOutput: 'Updated todo plan: Tool UI audit\n- [x] enumerate tools\n- [ ] capture screenshots',
    failError: 'todo_plan failed: document was changed by another window.',
  },
  {
    toolName: 'time',
    label: 'time',
    args: { action: 'diff', start_time: '2026-06-10T10:00:00+08:00', end_time: '2026-06-10T10:14:22+08:00', timezone: 'Asia/Shanghai' },
    doneOutput: 'Difference (end - start): 14 minutes 22 seconds\nMilliseconds: 862000\nSeconds: 862',
    failError: 'time failed: start_time is required for action="diff".',
  },
  {
    toolName: 'project_dirs',
    label: 'project_dirs',
    args: { action: 'add', path: ROOT, name: 'start-electron' },
    doneOutput: 'Added project directory: start-electron\n/Users/yitiansong/data/code/start-electron',
    failError: 'project_dirs failed: path is already registered with a different id.',
  },
  {
    toolName: 'skill',
    label: 'skill',
    args: { action: 'load', name: 'browser:control-in-app-browser' },
    doneOutput: 'Loaded skill browser:control-in-app-browser\nUse for local browser screenshots and interaction testing.',
    failError: 'skill failed: skill not found: missing-skill',
  },
  {
    toolName: 'web_search',
    label: 'web_search',
    args: { query: 'OpenAI Codex docs tool calls', count: 3, fetchPages: false },
    doneOutput: 'Search completed: 3 results.',
    failError: 'No web search provider configured. Please add a Brave Search API key in Settings -> Tools -> Web Search.',
    partial: textResult('Search completed: 3 results.', {
      phase: 'ready',
      searches: [{ query: 'OpenAI Codex docs tool calls', resultCount: 3 }],
      results: [
        { title: 'OpenAI Codex', url: 'https://developers.openai.com/codex', snippet: 'Build with Codex.' },
        { title: 'Tools', url: 'https://platform.openai.com/docs', snippet: 'Tool calling documentation.' },
      ],
    }),
  },
  {
    toolName: 'web_open',
    label: 'web_open',
    args: { url: 'https://platform.openai.com/docs/guides/tools', title: 'Tools guide' },
    doneOutput: 'Opened Tools guide\nReadable text extracted from platform.openai.com.',
    failError: 'web_open failed: fetch timed out after 10000ms.',
    partial: textResult('Opened Tools guide.', {
      phase: 'ready',
      pages: [{ title: 'Tools guide', url: 'https://platform.openai.com/docs/guides/tools', status: 'ready', text: 'Tool calling guide excerpt.' }],
    }),
  },
  {
    toolName: 'web_find',
    label: 'web_find',
    args: { url: 'https://platform.openai.com/docs/guides/tools', pattern: 'function calling' },
    doneOutput: 'Found 2 matches for "function calling".',
    failError: 'web_find failed: page has not been opened or cached.',
    partial: textResult('Found 2 matches.', {
      phase: 'ready',
      pages: [{ url: 'https://platform.openai.com/docs/guides/tools', status: 'ready' }],
      results: [{ line: 42, text: 'Function calling lets models choose tools.' }],
    }),
  },
  {
    toolName: 'fart',
    label: 'fart',
    args: { action: 'wave', text: 'Tool UI ready!' },
    doneOutput: [
      '--- frame 1/3 "ready" ---',
      ' /\\_/\\\\',
      '( o.o )',
      '--- frame 2/3 "ready" ---',
      ' /\\_/\\\\',
      '( -.- )',
      '--- frame 3/3 "ready" ---',
      ' /\\_/\\\\',
      '( o.o )',
    ].join('\n'),
    failError: 'fart failed: animation frame payload was invalid.',
  },
  {
    toolName: 'mcp_search',
    label: 'mcp_search',
    args: { action: 'call', tool: 'github.get_issue', arguments: { owner: 'openai', repo: 'codex', number: 42 } },
    doneOutput: 'Called MCP tool github.get_issue\nReturned issue title and labels.',
    failError: 'mcp_search failed: MCP server github is disconnected.',
  },
]

export const toolNames = specs.map(spec => spec.toolName)

function specFor(toolName: string): ToolSpec {
  const spec = specs.find(item => item.toolName === toolName)
  if (!spec) throw new Error(`Unknown tool fixture: ${toolName}`)
  return spec
}

function callId(toolName: string, state: string, index = 0): string {
  return `${toolName}-${state}-${index}`
}

function makeToolCall(spec: ToolSpec, state: ToolAuditState | 'streaming' | 'running', index = 0): ToolCall {
  const id = callId(spec.toolName, state, index)
  const status: ToolCall['status'] =
    state === 'permission'
      ? 'pending'
      : state === 'failed'
        ? 'failed'
        : state === 'streaming'
          ? 'input-streaming'
          : state === 'running'
            ? 'executing'
            : 'completed'

  return {
    id,
    toolId: spec.toolName,
    toolName: spec.toolName,
    arguments: state === 'streaming' ? {} : spec.args,
    status,
    timestamp: BASE_TIME + index * 100,
    startTime: BASE_TIME + index * 130,
    endTime: state === 'permission' || state === 'streaming' || state === 'running'
      ? undefined
      : BASE_TIME + index * 130 + 860 + index * 170,
    requiresConfirmation: state === 'permission' ? true : undefined,
    permissionId: state === 'permission' ? `${id}-permission` : undefined,
    canRespond: state === 'permission' ? true : undefined,
    changes: spec.changes && (state === 'completed' || state === 'expanded' || state === 'permission' || state === 'failed')
      ? spec.changes
      : undefined,
  }
}

function stepStatus(state: ToolAuditState | 'streaming' | 'running'): Step['status'] {
  if (state === 'permission') return 'awaiting-confirmation'
  if (state === 'failed') return 'failed'
  if (state === 'streaming' || state === 'running') return 'running'
  return 'completed'
}

function makeStep(spec: ToolSpec, state: ToolAuditState | 'streaming' | 'running', index = 0, updates: Partial<Step> = {}): Step {
  const toolCall = makeToolCall(spec, state, index)
  const isFailed = state === 'failed'
  const isDone = state === 'completed' || state === 'expanded'
  if (isDone) {
    toolCall.result = spec.toolName === 'fart'
      ? { output: spec.doneOutput, metadata: { phase: 'ready' } }
      : { output: spec.doneOutput }
  }
  if (isFailed) toolCall.error = spec.failError

  const partialResult = spec.partial && isDone
    ? spec.partial
    : isDone
      ? textResult(spec.doneOutput)
      : undefined

  return {
    id: `${toolCall.id}-step`,
    type: spec.toolName === 'bash' ? 'command' : 'tool-call',
    title: `${spec.label}: ${String(spec.args.path || spec.args.command || spec.args.query || spec.args.action || '')}`,
    status: stepStatus(state),
    timestamp: toolCall.timestamp,
    toolCallId: toolCall.id,
    toolCall,
    result: isDone ? JSON.stringify(toolCall.result) : undefined,
    partialResult,
    partialResultIsPartial: false,
    error: isFailed ? spec.failError : undefined,
    ...updates,
  }
}

export function buildToolAuditCase(toolName: string, state: ToolAuditState): ToolAuditCase {
  const spec = specFor(toolName)
  return {
    id: `${toolName}-${state}`,
    toolName,
    state,
    title: `${spec.label} / ${state}`,
    note: noteFor(toolName, state),
    steps: [makeStep(spec, state)],
    autoExpand: state === 'expanded',
  }
}

function noteFor(toolName: string, state: ToolAuditState): string {
  if (state === 'permission') return 'Permission waiting state: row status is derived from requiresConfirmation / awaiting-confirmation.'
  if (state === 'failed') return 'Failure state: row summary and inline details should expose actionable error text.'
  if (state === 'expanded') return 'Expanded state: this screenshot is produced by clicking the actual operation row after render.'
  if (toolName === 'read') return 'Read result should render content, but the renderer initially caps it to 8 lines.'
  if (toolName === 'edit' || toolName === 'write') return 'File mutation result should render diff details and theme-aware panel surfaces.'
  return 'Completed state: compact row plus detail payload available on expansion.'
}

export function buildFlowCases(): ToolAuditCase[] {
  const edit = specFor('edit')
  const bash = specFor('bash')
  const write = specFor('write')

  const editStart = makeStep(edit, 'streaming', 0)
  editStart.toolCall!.streamingArgs = '{"path":'

  const editStreaming = makeStep(edit, 'streaming', 1)
  editStreaming.toolCall!.streamingArgs = JSON.stringify({
    path: `${ROOT}/src/renderer/components/chat/StepsPanel.vue`,
    edits: [{ oldText: 'const label = "Tool"', newText: 'const label = "Tool activity"\nconst compact = true\n' }],
  }).slice(0, -3)

  const awaiting = makeStep(edit, 'permission', 2)

  const bashRunning = makeStep(bash, 'running', 3, {
    partialResult: textResult([
      '> make run',
      '[1/6] Compile AppKitBridge.swift',
      '[2/6] Compile ToolTimeline.swift',
      '[3/6] Link onething',
    ].join('\n')),
    partialResultIsPartial: true,
  })
  bashRunning.toolCall!.startTime = Date.now() - 7_200

  const bashDone = makeStep(bash, 'completed', 4)

  const writeStreaming = makeStep(write, 'streaming', 5)
  writeStreaming.toolCall!.streamingArgs = JSON.stringify({
    path: `${ROOT}/docs/tool-ui-audit/streaming-write.md`,
    content: '# Streaming write\n\nLine 1 appears first.\nLine 2 appears after another delta.\nLine 3 should scroll into view.\n',
  }).slice(0, -2)

  return [
    {
      id: 'flow-01-input-start',
      toolName: 'edit',
      state: 'flow',
      title: 'flow 01 / input-streaming starts',
      note: 'At the first tool-input delta, the row can only show the category verb and a generic target because the path is not complete yet.',
      steps: [editStart],
    },
    {
      id: 'flow-02-input-content',
      toolName: 'edit',
      state: 'flow',
      title: 'flow 02 / edit args stream content',
      note: 'Once path and newText are present, edit/write default-expand and render a synthetic added-lines diff while args are still incomplete.',
      steps: [editStreaming],
    },
    {
      id: 'flow-03-awaiting-permission',
      toolName: 'edit',
      state: 'flow',
      title: 'flow 03 / waiting for permission',
      note: 'Permission state collapses back to a row unless the user expands it; the pending diff exists but is not opened by default.',
      steps: [awaiting],
    },
    {
      id: 'flow-04-bash-linear-output',
      toolName: 'bash',
      state: 'flow',
      title: 'flow 04 / bash running output',
      note: 'Execution updates appear only inside expanded details; duration increments from startTime while status is executing.',
      steps: [bashRunning],
      autoExpand: true,
    },
    {
      id: 'flow-05-completed',
      toolName: 'bash',
      state: 'flow',
      title: 'flow 05 / completed output',
      note: 'After completion, result is final and duration stops at endTime.',
      steps: [bashDone],
      autoExpand: true,
    },
    {
      id: 'flow-06-write-streaming-content',
      toolName: 'write',
      state: 'flow',
      title: 'flow 06 / write content stream',
      note: 'Write content is parsed from streamingArgs and rendered as added diff rows before execution begins.',
      steps: [writeStreaming],
    },
  ]
}

export function buildGroupCase(kind: 'collapsed' | 'expanded' | 'hover'): ToolAuditCase {
  const edit = specFor('edit')
  const steps = [
    makeStep(edit, 'completed', 1),
    makeStep(edit, 'completed', 2, {
      toolCall: {
        ...makeToolCall(edit, 'completed', 2),
        arguments: { path: `${ROOT}/src/renderer/components/chat/ToolResultRenderer.vue`, edits: [{ oldText: 'old', newText: 'new' }] },
        changes: {
          diff: editDiff.replaceAll('StepsPanel.vue', 'ToolResultRenderer.vue'),
          filePath: `${ROOT}/src/renderer/components/chat/ToolResultRenderer.vue`,
          additions: 1,
          deletions: 1,
        },
      },
    }),
    makeStep(edit, 'completed', 3, {
      toolCall: {
        ...makeToolCall(edit, 'completed', 3),
        arguments: { path: `${ROOT}/src/renderer/components/chat/ToolDiffPreview.vue`, edits: [{ oldText: 'panel', newText: 'surface' }] },
        changes: {
          diff: editDiff.replaceAll('StepsPanel.vue', 'ToolDiffPreview.vue'),
          filePath: `${ROOT}/src/renderer/components/chat/ToolDiffPreview.vue`,
          additions: 2,
          deletions: 1,
        },
      },
    }),
  ]

  return {
    id: `edit-group-${kind}`,
    toolName: 'edit',
    state: 'group',
    title: `edit group / ${kind}`,
    note: 'Consecutive edit tools are merged into a workflow group. This case is used for collapsed, hover, and clicked-expanded interaction screenshots.',
    steps,
    autoExpand: kind === 'expanded',
  }
}

export function buildLongCommandCase(): ToolAuditCase {
  const bash = specFor('bash')
  const long = 'swift build --configuration debug --package-path /Users/yitiansong/data/code/start-electron/native/PanelBridge --scratch-path /tmp/onething-build-cache --verbose --triple arm64-apple-macosx15.0'
  return {
    id: 'bash-long-command',
    toolName: 'bash',
    state: 'permission',
    title: 'bash / long command title',
    note: 'Long bash commands are truncated before they reach the row title; permission panel title uses a separate 96-char truncation path.',
    steps: [makeStep({ ...bash, args: { command: long }, doneOutput: 'Done in 4.2s' }, 'permission')],
  }
}

export function allMatrixCases(): ToolAuditCase[] {
  return specs.flatMap(spec => (['permission', 'completed', 'failed', 'expanded'] as ToolAuditState[])
    .map(state => buildToolAuditCase(spec.toolName, state)))
}
