export {
  COLLAB_DEFAULT_MAX_CHAIN,
  COLLAB_DM_PAIR_MAX_CHAIN,
  COLLAB_HARVEST_SOURCE,
  COLLAB_MESSAGE_SOURCE,
  COLLAB_USAGE_SOURCE_ROOM,
  COLLAB_USAGE_SOURCE_WORK,
  isCollabDriveMessage,
  isCollabHarvestMessage,
  type CollabAgentLike,
  type CollabMentionLike,
  type CollabMessageLike,
  type CollabReplyToLike,
  type CollabRoomBudgets,
  type CollabRoomConfig,
  type CollabSessionKind,
} from './types.js'
/** R3: what a room message IS, decided in one place. The predicates above (and
 *  in say.js / system-lines.js) all delegate here. */
export {
  classifyCollabRoomMessage,
  type CollabRoomMessageKind,
} from './classify.js'
export { COLLAB_PASS_SENTINEL, isCollabPassMessage } from './pass.js'
export { COLLAB_CONSUMED_SCAN_TAIL, collectConsumedSourceIds } from './reconcile.js'
export {
  COLLAB_AGENT_SESSION_NAME_PREFIX,
  COLLAB_AGENT_SESSION_PREFIX,
  collabAgentSessionId,
  collabAgentSessionIdsForScan,
  collabAgentSessionName,
  isCollabAgentSessionId,
  stripCollabAgentSessionName,
} from './agent-session.js'
export {
  COLLAB_SAY_MAX_CHARS,
  COLLAB_SAY_REFUSED_BUDGET,
  COLLAB_SAY_REFUSED_EMPTY,
  COLLAB_SAY_REFUSED_FROZEN,
  COLLAB_SAY_REFUSED_NOT_MEMBER,
  COLLAB_SAY_REFUSED_NO_ROOM,
  COLLAB_SAY_REFUSED_UNKNOWN_ROOM,
  COLLAB_SAY_SOURCE,
  COLLAB_SAY_TOOL_NAME,
  COLLAB_TURN_SOURCE,
  formatCollabSayReceipt,
  formatCollabThinkingTraceLabel,
  isCollabSayMessage,
  isCollabThinkingMessage,
  normalizeCollabSayContent,
  resolveCollabSayMentions,
  resolveCollabSayRoomSessionId,
  type CollabTurnToolCallLike,
} from './say.js'
export {
  buildCollabCommonRules,
  buildCollabWorkRules,
} from './agent-rules.js'
export {
  COLLAB_CARD_SHORT_ID_CHARS,
  formatCollabCardShortId,
  matchCollabInlineTagAt,
  parseCollabInlineSegments,
  renderCollabInlineTagsAsText,
  sanitizeCollabInlineMarkup,
  type CollabInlineCardSegment,
  type CollabInlineFileSegment,
  type CollabInlineSegment,
  type CollabInlineTagMatch,
  type CollabInlineTagName,
  type CollabInlineTextSegment,
} from './inline-tags.js'
export {
  COLLAB_TURN_MAX_SAY_CALLS,
  COLLAB_TURN_MAX_TOOL_CALLS,
  createCollabTurnCircuitBreaker,
  formatCollabTurnBreakerNote,
  resolveCollabTurnBreakerLimits,
  type CollabTurnBreakerLimits,
  type CollabTurnBreakerSignal,
  type CollabTurnBreakerTrip,
  type CollabTurnCircuitBreaker,
} from './circuit-breaker.js'
export {
  createCollabTypingTracker,
  type CollabTypingSignal,
  type CollabTypingTracker,
} from './typing.js'
export {
  COLLAB_REACTION_EMOJIS,
  COLLAB_REACTION_SUMMARY_MAX_ENTRIES,
  addCollabReaction,
  appendCollabReactionSummary,
  applyCollabReaction,
  formatCollabReactionSummary,
  hasCollabReactionFrom,
  isSameCollabReactionActor,
  normalizeCollabReactionEmoji,
  tallyCollabReactions,
  toggleCollabReaction,
  type ApplyCollabReactionOptions,
  type CollabReactionActorLike,
  type CollabReactionEmoji,
  type CollabReactionLike,
  type CollabReactionTally,
} from './reactions.js'
export {
  applyCollabBoardAction,
  emptyCollabBoard,
  renderCollabAgentRef,
  renderCollabBoardDigest,
  COLLAB_BLOCK_REASON_MAX_CHARS,
  COLLAB_MAX_HALTS,
  COLLAB_MAX_REJECTIONS,
  COLLAB_REPORT_SUMMARY_MAX_CHARS,
  COLLAB_TASK_STATUSES,
  type ApplyCollabBoardActionResult,
  type CollabBoard,
  type CollabBoardAction,
  type CollabBoardActor,
  type CollabBoardEvent,
  type CollabBoardSelf,
  type CollabTask,
  type CollabTaskEvidence,
  type CollabTaskStatus,
} from './board.js'
export {
  buildCollabMentions,
  mergeCollabMentions,
  normalizeCollabMentions,
  parseCollabMentions,
  renderCollabMentionText,
  resolveCollabMentionIds,
} from './mentions.js'
export {
  COLLAB_REPLY_EXCERPT_MAX_CHARS,
  COLLAB_REPLY_UNKNOWN_AUTHOR_LABEL,
  COLLAB_REPLY_USER_LABEL,
  buildCollabReplyToSnapshot,
  condenseCollabReplyExcerpt,
  countCollabVisibleMessagesBetween,
  isCollabVisibleRoomMessage,
  shouldAttachCollabReplyTo,
  type BuildCollabReplyToSnapshotOptions,
  type CollabReplyGapOptions,
} from './reply-quote.js'
export {
  COLLAB_ENVELOPE_TAG,
  formatCollabFlattenedToolCall,
  formatCollabReplyQuote,
  wrapCollabMessageEnvelope,
  mergeCollabProjectedRows,
  projectRoomHistory,
  type CollabProjectedRowLike,
  type MergeCollabProjectedRowsOptions,
  type ProjectedRoomMessage,
  type ProjectRoomHistoryOptions,
} from './projection.js'
export {
  decideCollabActivations,
  formatCollabActivationLabel,
  resolveCollabChainCap,
  COLLAB_ACTIVATION_LABELS,
  COLLAB_DRIVE_LABEL_TASK_ASSIGNED,
  COLLAB_DRIVE_LABEL_TASK_HALTED,
  COLLAB_DRIVE_LABEL_TASK_REVIEW,
  type CollabActivationReason,
  type CollabActivationRequest,
  type DecideCollabActivationsOptions,
  type DecideCollabActivationsResult,
} from './activation.js'
export {
  buildCollabRoomContext,
  buildCollabRoomSystemPrompt,
  resolveCollabSpeakerLabel,
  formatCollabSelfTaskFacts,
  type BuildCollabRoomContextOptions,
  type BuildCollabRoomSystemPromptOptions,
  type CollabSelfTaskFact,
  type CollabSelfTaskStatus,
} from './roster.js'
export {
  buildCollabMemberJoinedLine,
  buildCollabMemberRemovedLine,
  buildCollabMembershipLines,
  buildCollabPmAssignedLine,
  buildCollabPmClearedLine,
  buildCollabSilentDeliveryLine,
  buildCollabTaskAssignedLine,
  buildCollabTaskDeliveredLine,
  buildCollabTaskDoneLine,
  buildCollabTaskHaltCapLine,
  buildCollabTaskHaltedLine,
  buildCollabTaskInterruptedLine,
  buildCollabTaskRequeueRefusedLine,
  excerptCollabHaltReason,
  formatCollabProjectedSystemLine,
  formatCollabTaskEvidence,
  isCollabProjectedSystemLine,
  type CollabMembershipChangeOptions,
  COLLAB_HALT_REASON_EXCERPT_CHARS,
  COLLAB_NO_EVIDENCE_TEXT,
  COLLAB_SILENT_SUMMARY_EXCERPT_CHARS,
  COLLAB_PROJECTED_SYSTEM_SOURCES,
  COLLAB_SYSTEM_SOURCE_MEMBERSHIP,
  COLLAB_SYSTEM_SOURCE_TASK,
  COLLAB_SYSTEM_SPEAKER_LABEL,
  COLLAB_TASK_HALTED_DISPOSITION,
} from './system-lines.js'
export {
  filterCollabSelfElectCandidates,
  isCollabConversationMessage,
  isCollabProjectedRoomMessage,
  selectRecentCollabConversationMessages,
  selectRecentCollabProjectedMessages,
  COLLAB_SELF_ELECT_COOLDOWN,
} from './cooldown.js'
export {
  buildWillingnessPrompt,
  buildWillingnessWindow,
  parseWillingnessReply,
  COLLAB_WILLINGNESS_LINE_LIMIT,
  COLLAB_WILLINGNESS_PM_FACT,
  COLLAB_WILLINGNESS_QUESTION,
  COLLAB_WILLINGNESS_RECENT_LIMIT,
  type BuildWillingnessPromptOptions,
  type CollabWillingnessPrompt,
  type CollabWillingnessVerdict,
} from './willingness.js'
export {
  COLLAB_ROOM_TOOLS,
  COLLAB_WORK_REQUIRED_TOOLS,
  resolveCollabToolAllowlist,
} from './tool-surface.js'
export {
  isAgentPairDmRoom,
  isUserDmRoom,
  type CollabDmRoomLike,
} from './dm.js'
export {
  collabMessageCountsTowardChain,
  collabMessageResetsChain,
  computeCollabChainCount,
} from './chain.js'
